### ISSUE TITLE
Tracks overlapping

### ISSUE THREAD

**Issue by loeffelpan** [librespot-org/librespot-java#102]
I’m listening to an audiobook.
Sometimes (not with every track) tracks are overlapping about half a second.
Next track starts to play just a bit before previous track ends.

Preloading is enabled.

**Comment by devgianlu** [comment]
That's probably caused that the next track starts when the player finishes reading the body, not when it actually ends playing.

**Comment by loeffelpan** [comment]
Just tested this commit with another audiobook.
Overlapping is fixed, but now playback not gapless anymore. There is a very little gap between tracks.

**Comment by devgianlu** [comment]
That could be indeed an issue with the mixer itself, rather than `librespot-java`.
