### ISSUE TITLE
Playback (saw that in log) but nothing to hear

### ISSUE THREAD

**Issue by loeffelpan** [librespot-org/librespot-java#106]
Got this after changing the album and nothing was to hear.
I saw the tracks/chunks going on in the the log, but after this maybe the line was closed?
Never saw a line reused before.

`2019-07-06 10:55:06 TRACE LinesHolder:132 - Reused line for mixer 'Device [default]'.`

**Comment by devgianlu** [comment]
There's a small chance that this happens, I don't quite know why and most importantly it's not easily reproducible. 

The reused thing is completely normal, it's part of the changes to remove the popping noise and makes the playback better overall.

I'll try to review the code to see if there's anything wrong.
