### ISSUE TITLE
Branch new-spotify-api -> librespot-core not working

### ISSUE THREAD

**Issue by zerginator** [librespot-org/librespot-java#107]
**Describe the bug**
module librespot-core -> Main.class stops unexpected with the last message in the logs:
SpotifyConnect service registered successfully!

but no further message and the client doesnt show up on my phone spotify or on my desktop spotify

**To Reproduce**
Steps to reproduce the behavior.
1. start Main class in librespot-core
2. last message in the logs: "SpotifyConnect service registered successfully!"

**Expected behavior**
Client should show up in the spotify app again

**Screenshots/Stracktraces/Logs**
Screenshots if applicable, stacktrace and log is a crash occurred.

![image](https://user-images.githubusercontent.com/2770344/61188829-43363d00-a685-11e9-8792-7d39e991f8b7.png)

**Version/Commit**
Version used or commit pulled if compiled locally.
branch new-spotify-api -> librespot-core

**Comment by devgianlu** [comment]
This is a warning saying that the Spotify service couldn't be dispatched on that interface, it should work normally.

For the fact that it doesn't show up, there could be different reasons: one of which could be your router, please check if it says anything about mDNS or multicast. 

In the meantime, you can use another authentication method to run it (USER_PASS or FACEBOOK).

**Comment by zerginator** [comment]
Ok never mind. although i got some warnings in new-spotify-api, but maybe means nothing.....
![image](https://user-images.githubusercontent.com/2770344/61228571-cf4c7100-a726-11e9-94e1-deb199e14066.png)

**Comment by devgianlu** [comment]
That's fine, we never reverse engineered the response for `GET /` because it works anyway. From the logs I see it is working now, correct?

**Comment by zerginator** [comment]
yes i can confirm that its working. i can see it now in my laptops spotify
