### ISSUE TITLE
exit application when no network is ready 

### ISSUE THREAD

**Issue by zerginator** [librespot-org/librespot-java#108]
**Is your feature request related to a problem? Please describe.**
Please check if you reach the internet (for example ping google.com or something) when starting the app. If no network is up ->  exit application
 
Currently i have the problem with the app raspotify and systemd with the OS raspbian buster ( Debian ) . The desktop environment LXDE doesnt support network discovery ( network.target or network-online.target)

I made a workaround with waiting 15 seconds but that sucks because of various reasons. Easier would it be if you could just terminate the app when no internet connection is there, than i could tell systemd to restart the librespot-java until internet is up
 
What do you think ?

**Comment by devgianlu** [comment]
Have a look at #46, which is about the same issue. Have you tried https://github.com/librespot-org/librespot-java/issues/46#issuecomment-473178121?

**Comment by zerginator** [comment]
up thats a duplicate , sorry about that
