### ISSUE TITLE
v.0.6.1 ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by zerginator** [librespot-org/librespot-java#113]
**Describe the bug**
When trying to connect with app over an Android phone i got the following Exception:

```
Jul 19 12:43:56 raspberrypi java[1217]: 2019-07-19 12:43:56 TRACE SpotifyIrc:119 - Frame sent successfully, type: kMessageTypeNotify
Jul 19 12:43:56 raspberrypi java[1217]: 2019-07-19 12:43:56 TRACE CdnManager:274 - Chunk 38/149 completed, cdn: podcasts.cnn.net, cached: false, stream: {episodeGid: B17A934EA28B5CA5B57609F26307B7C
Jul 19 12:43:57 raspberrypi java[1217]: 2019-07-19 12:43:57 TRACE CdnManager:274 - Chunk 36/149 completed, cdn: podcasts.cnn.net, cached: false, stream: {episodeGid: B17A934EA28B5CA5B57609F26307B7C
Jul 19 12:43:57 raspberrypi java[1217]: 2019-07-19 12:43:57 DEBUG Player:340 - Playback resumed, chunk 36 retrieved, took 1525ms.
Jul 19 12:43:57 raspberrypi java[1217]: 2019-07-19 12:43:57 TRACE SpotifyIrc:105 - Send frame, type: kMessageTypeNotify
Jul 19 12:43:57 raspberrypi java[1217]: 2019-07-19 12:43:57 TRACE MercuryClient:131 - Send Mercury request, seq: 7, uri: hm://remote/3/user/XXXXXXXXXXXX/, method: POST
Jul 19 12:43:57 raspberrypi java[1217]: 2019-07-19 12:43:57 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 7, flags: 1, parts: 1
Jul 19 12:43:57 raspberrypi java[1217]: 2019-07-19 12:43:57 TRACE SpotifyIrc:119 - Frame sent successfully, type: kMessageTypeNotify
Jul 19 12:43:57 raspberrypi java[1217]: Exception in thread "player-runner-XXXXXX" java.lang.ArrayIndexOutOfBoundsException: arraycopy: source index -133 out of bounds for byte[1024]
Jul 19 12:43:57 raspberrypi java[1217]:         at java.base/java.lang.System.arraycopy(Native Method)
Jul 19 12:43:57 raspberrypi java[1217]:         at xyz.gianlu.librespot.player.codecs.mp3.Decoder.samples_III(Decoder.java:647)
Jul 19 12:43:57 raspberrypi java[1217]:         at xyz.gianlu.librespot.player.codecs.mp3.Decoder.decodeFrame(Decoder.java:568)
Jul 19 12:43:57 raspberrypi java[1217]:         at xyz.gianlu.librespot.player.codecs.mp3.Decoder.decodeFrame(Decoder.java:488)
Jul 19 12:43:57 raspberrypi java[1217]:         at xyz.gianlu.librespot.player.codecs.mp3.Mp3Sound.read(Mp3Sound.java:107)
Jul 19 12:43:57 raspberrypi java[1217]:         at xyz.gianlu.librespot.player.codecs.mp3.Mp3Sound.read(Mp3Sound.java:87)
Jul 19 12:43:57 raspberrypi java[1217]:         at xyz.gianlu.librespot.player.codecs.Mp3Codec.readBody(Mp3Codec.java:68)
Jul 19 12:43:57 raspberrypi java[1217]:         at xyz.gianlu.librespot.player.codecs.Codec.run(Codec.java:68)
Jul 19 12:43:57 raspberrypi java[1217]:         at xyz.gianlu.librespot.player.PlayerRunner.run(PlayerRunner.java:41)
Jul 19 12:43:57 raspberrypi java[1217]:         at java.base/java.lang.Thread.run(Thread.java:834)
Jul 19 12:44:46 raspberrypi java[1217]: 2019-07-19 12:44:46 TRACE MercuryClient:173 - Handling packet, cmd: MercuryEvent, seq: -3353488474484244480, flags: 1, parts: 2
Jul 19 12:44:46 raspberrypi java[1217]: 2019-07-19 12:44:46 TRACE SpotifyIrc:195 - Handling frame, type: kMessageTypeNotify, ident: XXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Version/Commit**
0.6.1

**Comment by devgianlu** [comment]
I suppose you were playing an episode? Could you tell me which one?

**Comment by spocon** [comment]
It was this one : https://open.spotify.com/episode/5oTERc2hcfzlmrmQ2aQYcL?si=04qDSeMpTwqTwY0GtBdJiA

**Comment by devgianlu** [comment]
I'll have a look.

**Comment by zerginator** [comment]
yes that was the episode

**Comment by devgianlu** [comment]
I've changed the MP3 decoding library, this should happen no more.

**Comment by msmucr** [comment]
Hello,
I'm experiencing similar issue also with recent 1.4.0 release.
Not sure, what exactly is going on with this podcast shows with episodes, but for example it isn't possible to play any episode from there.
https://open.spotify.com/show/14U2pJ15Ix5x838NXqt1zJ

It always ends up with the message about MP3 decoder

`java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
	at xyz.gianlu.librespot.player.codecs.Mp3Codec$Mp3InputStream.<init>(Mp3Codec.java:105) ~[librespot-core-jar-with-dependencies.jar:1.4.0]
	at xyz.gianlu.librespot.player.codecs.Mp3Codec.<init>(Mp3Codec.java:27) ~[librespot-core-jar-with-dependencies.jar:1.4.0]
	at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.load(PlayerQueueEntry.java:112) ~[librespot-core-jar-with-dependencies.jar:1.4.0]
	at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.run(PlayerQueueEntry.java:248) ~[librespot-core-jar-with-dependencies.jar:1.4.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
`

All the best,

Michal

**Comment by devgianlu** [comment]
Which version of Java are you using?

**Comment by msmucr** [comment]
I've tried OpenJDK 1.8.0_252 on Linux (Centos 8 with Java from distribution repo) and Oracle Java 1.8.0_241 and 1.8.0_251 on Windows 10.
The podcast is playable with your JRE?

Thank you!

**Comment by devgianlu** [comment]
Java 9 should fix this issue, but it would nice to figure out why its happening.

https://github.com/eclipse/jetty.project/issues/3244
https://github.com/blynkkk/blynk-server/issues/752

**Comment by msmucr** [comment]
The newer JRE indeed helps with that, I've just tried openjdk-11 and it works perfectly. For some reason, I had Java 8 for some other tools, I use at the same system, and I've not yet tried everything with Java 11 (shame, I know ;) so I've sticked with default Java 8.
Maybe I could also try to build it with your recent commit and report back, whether it helped with Java 8 compatiblity.

Thank you so much!

**Comment by msmucr** [comment]
O.K. I've got that now, sorry. The commit was affecting just automatic build with Travis CI here, eg. next release.
So I've got Maven and stuff, cloned the repo, rebuild that with OpenJDK 8.
As I've tested it, it works fine with both Java 8 and Java 11 JREs. Perfect!
