### ISSUE TITLE
Why move JavaMP3 inside the project rather than depending on it?

### ISSUE THREAD

**Issue by delthas** [librespot-org/librespot-java#118]
Just a question out of curiosity: why did you decide to move JavaMP3 in the project rather than depend on it thru maven? in commit e2da7a6

**Comment by devgianlu** [comment]
I needed to make some important modifications like pregain and fix a nasty bug for which I've also created a PR on your repo. Since it was only two files, I moved and added it to the LICENSE file.

**Comment by delthas** [comment]
I see, thanks.
