### ISSUE TITLE
Synchronization issue with Spotify client

### ISSUE THREAD

**Issue by devgianlu** [librespot-org/librespot-java#12]
Issue 1:
- Play song from stopped state
- Time bar jumps to the end of the song on the client
- Pause and play
- Time is now correct

Issue 2:
- Let song play
- Pause 
- Time goes forward a couple of seconds
- Play
- Time goes back a couple of seconds (as was before before pause)

**Comment by elganzua124** [comment]
Maybe it gives you some hints: https://github.com/librespot-org/librespot/issues/210

**Comment by devgianlu** [comment]
Nice catch, I'll try to use `kPlayStatusLoading`.

**Comment by devgianlu** [comment]
That didn't fix the issue, apart from the buffering one. (updated the main post with a better description)

**Comment by sashahilton00** [comment]
This also happens when the next song loads. Pausing and unpausing doesn't seem to fix it, only seeking does, and even then we still see the progress bar jump when pausing. In addition restarting the track causes the progress bar to jump to the end.

**Comment by devgianlu** [comment]
This fixed itself by using the new endpoint.

**Comment by sashahilton00** [comment]
The recent commits in remote-3 branch? will give it a go.

**Comment by devgianlu** [comment]
Yep, I've just merged it with master.

**Comment by sashahilton00** [comment]
so i saw. building now.

**Comment by devgianlu** [comment]
I had some issues with Git, pull now.

**Comment by sashahilton00** [comment]
fixed some of the issues, though I noticed that the progress bar doesn't move for the first 15 seconds of any song now for some reason. I note that the bar starts moving a split second before the client logs receiving the 3rd chunk.

**Comment by devgianlu** [comment]
Fixed by c35f37fe108d299e65bea1f0b439d807dd0c92c9
