### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by Pibben** [librespot-org/librespot-java#124]
I tried to find any search functionality in the lib, but failed. Is this missing? Is there a plan to add it?

**Comment by devgianlu** [comment]
Currently missing, I will find the time to implement in the near feature.

**Comment by devgianlu** [comment]
I've added this feature to the `new-spotify-api` branch (#105). You can use it as follows:
```
Session session = new Session.Builder(new FileConfiguration()).create();
JsonObject result = session.search().request(new SearchManager.SearchRequest("test123"));
System.out.println(result);
```
