### ISSUE TITLE
Played just one song and instance exited

### ISSUE THREAD

**Issue by leafy7382** [librespot-org/librespot-java#135]
Started the instance with
java -jar librespot-core-jar-with-dependencies.jar >info.log 2>&1 &

and played only 1 song, after the song ended, the instance exited.

Attaching the log for reference, latest version on spotify-new-api
[info.log](https://github.com/librespot-org/librespot-java/files/3612324/info.log)

**Comment by devgianlu** [comment]
This happened because the client can't apparently load an autoplay for search queries. The client will now simply pause.
