### ISSUE TITLE
NullPointerException while establishing session

### ISSUE THREAD

**Issue by Kucheek** [librespot-org/librespot-java#139]
With the fix done for issue #137 , I cannot connect to librespot at all. There is a NullPointerException in zeroconf client. See
[nohup.txt](https://github.com/librespot-org/librespot-java/files/3625134/nohup.txt)

Commit 6f44c38

**Comment by devgianlu** [comment]
Should be fixed. I'll leave this open because the logs clearly shows that the client reattempted to connect while it had already connected. This has to be investigated.

**Comment by Kucheek** [comment]
Tried now with https://github.com/librespot-org/librespot-java/commit/268d4f1e101131312533833ccaba1ab52b9d96ca, got connected and started playback in the end, so the fix helped. But still some exceptions appeared on the way. Have a look: 
[nohup.txt](https://github.com/librespot-org/librespot-java/files/3626869/nohup.txt)

**Comment by devgianlu** [comment]
Yeah, it is related to the thing I've mentioned above. I'll leave them there for now since they don't compromise the functionality of the application. 

They'll disappear whenever I fix the connection reattempt issue.
