### ISSUE TITLE
cannot connect to api server

### ISSUE THREAD

**Issue by elganzua124** [librespot-org/librespot-java#148]
**Describe the bug**
   The api-client cannot conect to the api server.

**To Reproduce**
While librespot-api is running, open the api-client, set the field to ws://localhost:24879, click on connect. Nothing happens.

**Expected behavior**
Following the steps previously described, the api-client should connect to the api server.

**Screenshots/Stracktraces/Logs**
Screenshots if applicable, stacktrace and log is a crash occurred.

**Version/Commit**
Librespot-api compiled with maven from branch dev.

**Comment by devgianlu** [comment]
The `api-client` has been removed and won't be available anymore in future releases. It was too bulky and unnecessary as part of this project. It is equally simple to just use curl.

**Comment by elganzua124** [comment]
Ok, thanks for the quick response. So all the API logic will be removed from librespot-java?

**Comment by devgianlu** [comment]
The API logic will remain. I have modified it a little bit to make lighter, but I am happy to improve it as I don't use it much.

**Comment by elganzua124** [comment]
Thanks, so how do I establish the connection?

**Comment by devgianlu** [comment]
I have updated the [README](https://github.com/librespot-org/librespot-java/blob/master/api/README.md) right now.

**Comment by elganzua124** [comment]
Thanks a lot!
