### ISSUE TITLE
Add support for retrieve basic metadata from api server.

### ISSUE THREAD

**Issue by elganzua124** [librespot-org/librespot-java#149]
In my current project, besides controlling the playback, I need to show on a 128x64 glcd display the name of the current track, the artist and the album. Is it feasible to add that functionality?

**Comment by devgianlu** [comment]
I've updated the [README](https://github.com/librespot-org/librespot-java/tree/dev/api) with more details about the usage.

**Comment by elganzua124** [comment]
Great, thanks. How do I get the uri of the current track? I was thinking on an endpoint like `\player\current` that give us the uri of the current track.

**Comment by devgianlu** [comment]
> Great, thanks. How do I get the uri of the current track? I was thinking on an endpoint like `\player\current` that give us the uri of the current track.

Done.

**Comment by uvjustin** [comment]
Just an innocent question - is the type in the "\metadata\{type}\{uri}" endpoint necessary? Isn't that info already in the uri?

**Comment by devgianlu** [comment]
> Just an innocent question - is the type in the "\metadata{type}{uri}" endpoint necessary? Isn't that info already in the uri?

It may be, but I've done it this way to avoid requesting metadata for something that isn't what you want. I could probably add a shortcut metadata that guesses the type and does the thing.
