### ISSUE TITLE
Unshuffle playlist

### ISSUE THREAD

**Issue by devgianlu** [librespot-org/librespot-java#15]
Everything goes well when going from "do not shuffle" to "shuffle". The problem is from "shuffle" to "do not shuffle": **how do I bring back the "not shuffled" playlist?** It does not appear to be sent with the frame.

**Comment by sashahilton00** [comment]
You'll need to get the context from the state. the way librespot handles it is that when `kMessageTypeShuffle` is received, the song queue is randomly shuffled if the shuffle state is set to true. When set to false, the context is retrieved from the state to get the ordered list of tracks back. See https://github.com/librespot-org/librespot/blob/431be9e847a584d374ec44e7c138525dd8fbb9d6/connect/src/spirc.rs#L503 for implementation details.

**Comment by devgianlu** [comment]
I don't get it, all I see is the context uri being logged.

**Comment by sashahilton00** [comment]
the shuffle happens locally. the context never changes from pressing the shuffle button. So you get the context, shuffle it, and then play it. you can see this in action in the Spotify client. if you shuffle a playlist, the list doesn't change, rather the green selected bar jumps around the playlist, as the shuffled state is only recorded internally. to unshuffle, get the index of the currently played song from the context, then queue all the songs that follow it. 

i.e. you internally shuffle things, then to unshuffle, just check the index of the current song in the context, and queue the songs that follow it.

**Comment by devgianlu** [comment]
So, I have to retrieve the tracks in the playlist separately? I thought there was a simpler way. Also, has this been implemented in `librespot`? It doesn't look like.

**Comment by sashahilton00** [comment]
I'm not really understanding what you're trying to do. Presumably if do not shuffle to shuffle works for you, then you have implemented the shuffle logic, in which case you can implement a method to disable shuffle? For example, if you have the array of tracks stored as `['a', 'b', 'c', 'd']`, and you want to shuffle, just select a random index for the next track instead of `current index + 1`. To unshuffle, revert to the normal behaviour for selecting the next track `current index + 1`. Am I missing something here?

**Comment by devgianlu** [comment]
I've just tested this with `librespot` and it is having the same issue as I am. I don't think it has been implemented.

**Comment by sashahilton00** [comment]
I'm blind. Just reread the code, you're right, not implemented. Still, method stands, re-retrieve context, or store playlist and just toggle sequential vs random index selection

**Comment by devgianlu** [comment]
https://github.com/librespot-org/librespot/issues/264

**Comment by devgianlu** [comment]
When trying to unshuffle big playlists, the server answer with 500 when sending the state update. This could be related to the payload being too large, but this isn't an issue when shuffling.

**Comment by devgianlu** [comment]
I'm now using Fisher-Yates and it works pretty well. It cannot unshuffle if the playlist is already shuffled but I  think it's fine for now.
