### ISSUE TITLE
Share mixer line with other apps in environment with sound subsystem limitations

### ISSUE THREAD

**Issue by Kucheek** [librespot-org/librespot-java#150]
Please implement a logic to release (close) the mixer line when not in use.

Currently, after playback is started for the first time in librespot-java instance on RaspberryPi platform, other applications lose the access to soundcard over mixer line even at times when librespot-java is idle because it keeps holding the mixer line opened infinitely. Due to sound subsystem limitations of  RaspberryPi, the line cannot be used by multiple processes at the same time. 

**Is your feature request related to a problem? Please describe.**

When I want to play something in Kodi at the moment when playback in librespot-java is not running, Kodi throws following error:

17:12:22.536 T:2953827072   ERROR: CAESinkALSA::Initialize - failed to initialize device "@"

...where "@" in my case stands for the soundcard providing the mixer configured in librespot:

16:58:22.355 T:2991411200  NOTICE: Enumerated ALSA devices:
16:58:22.355 T:2991411200  NOTICE:     Device 1
16:58:22.356 T:2991411200  NOTICE:         m_deviceName      : @
16:58:22.356 T:2991411200  NOTICE:         m_displayName     : Default (snd_rpi_hifiberry_dacplus Analog)
16:58:22.356 T:2991411200  NOTICE:         m_displayNameExtra:
16:58:22.356 T:2991411200  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
16:58:22.356 T:2991411200  NOTICE:         m_channels        : FL,FR
16:58:22.356 T:2991411200  NOTICE:         m_sampleRates     : 8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
16:58:22.356 T:2991411200  NOTICE:         m_dataFormats     : AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE
16:58:22.356 T:2991411200  NOTICE:         m_streamTypes     : No passthrough capabilities

As a workaround, I currently restart the whole system to be able to start playback in Kodi. This is not very user-friendly on my system which is running headless. Also this is a no-go for a user with limited technical skills and knowledge (wife, kids).

The root cause is described in this article:

_The Raspberry Pi ASoc sound subsystem does not allow concurrent access to the sound card from multiple processes. Therefore if you already have a process running that uses your HiFiBerry sound card to play back something, you can't have another process accessing the driver. Depending on the program you use, you will get a more or less readable error message. This even happens if one process isn't really playing something, but has blocked the sound card. Many programs do this._
https://support.hifiberry.com/hc/en-us/articles/207397665-Mixing-different-audio-sources 

Preconditions:

RaspberryPi with ASoc sound subsystem in use
librespot-java and any other audio playback application installed, both configured to use mixer output

Steps to reproduce:

1. Start instances of librespot-java and any other audio playback application (let's assume Kodi in this case) on the hw configuration from Preconditions
2. Initiate playback in Kodi
- playback starts successfully in Kodi
3. Stop playback in Kodi
4. Initiate playback in librespot-java
- playback starts successfully in librespot-java
5. Stop playback in librespot-java
6. Initiate playback in Kodi
- playback does not start in Kodi, error occurs

**Describe the solution you'd like**

Close the line when playback is not active (paused manually by user, different target device was chosen, end of queue / playlist has been reached), as documented here:

_When a line opens, it reserves system resources for itself, and when it closes, these resources are freed for other objects or applications._
https://docs.oracle.com/javase/7/docs/api/javax/sound/sampled/Line.html

As a source of inspiration, you can also check Kodi which has a logic implemented that releases the line after some time of idleness (configurable delay).

**Describe alternatives you've considered**

**A)** Keep restarting the system each time I want to play something in other application. Either by physically disconnecting and reconnecting power source line to Rpi (not preferred) or with a command (over ssh, using remote which calls Kodi API). 

**B)** Use different output method (pipe, stdout) in librespot-java to avoid collision when accessing mixer line. Redirect pipe or stdout as a stream to Kodi (not sure if it is possible, the only addon I found https://github.com/metal3d/idok is long deprecated and with unresolved issues). Switch in Kodi between the stream and other content as required.

**C)** Configure dmix ALSA module to create a ALSA device that allows simultaneous playback as described in https://support.hifiberry.com/hc/en-us/articles/207397665-Mixing-different-audio-sources Already tried to configure that but it was not working with my configuration. Might be the solution is no longer valid on current raspbian releases.

**D)** Try to use pulseaudio somehow, but it is not recommended on low performance HW like RaspberryPi 1B as it is resource demanding.

**Comment by devgianlu** [comment]
Done. Let me know if it works. The delay is set to 20 seconds by default and can be adjusted with `player.releaseLineDelay`.

**Comment by Kucheek** [comment]
Wow, that was fast. I'll get a chance to try it later today. I'll let you know the results. Thanks!

**Comment by Kucheek** [comment]
The feature is working fine. So far I tried the most important scenario for me where I pause librespot manually, switch to Kodi where I start playback without problem, later stop it, return back to librespot and resume where I left. I will focus on more scenarios now.

The only issue I observe (actually hear, because it is deafening) is that when line is retaken back by librespot, the volume defaults to max (65536). My default and usual setting is 3000, so I have to quickly turn it down. I made sure that Kodi volume setting has no effect on the behavior - it is independent, no matter how loud I had left Kodi. 

Probably volume has to be reset when re-opening the line in librespot?

**Comment by devgianlu** [comment]
I've pushed a fix.

**Comment by Kucheek** [comment]
Thank you, now volume setting is applied correctly after the line is reopened.

**Comment by attilioscot** [comment]
Hi! I have one small issue related to this one: on startup the app still acquires the line, and doesn't release it unless you first start and then stop/pause playback.
I'm using pulseaudio, so other apps can concurrently use the sound card, but this behavior still keeps my audio device running all the time until the first pause event, which is a problem in my setup, and generally increases power consumption.
