### ISSUE TITLE
Question: Monitor for events?

### ISSUE THREAD

**Issue by eoware** [librespot-org/librespot-java#153]
Does librespot-java support any kind of event mechanism? The original used an --onevent to specify a a process to run on player events. It looks like there used to be a websocket API, but it's now just a POST-based web api. Is there any way to monitor for events?

**Comment by devgianlu** [comment]
The websocket API has been removed because it was pretty useless. I can reintroduce it with the purpose of notifying events.

The --onevent technique that librespot is also feasible, once all the listeners are in place, it shouldn't be a big deal.

I will work on that.

**Comment by devgianlu** [comment]
I've implemented the WebSocket API (63f901a2915136f200a83c8abb3fd32b4a342149). Let me know what you think. I've also updated the [README](https://github.com/librespot-org/librespot-java/tree/dev/api#events) with some more information.

**Comment by eoware** [comment]
Looks good! Will this send an onTrackChanged at around the same time (right before or after) the onPlaybackResumed?

**Comment by devgianlu** [comment]
When starting playback for the first time, you'll receive the following events:
- `playbackResumed`
- `contextChanged`
- `trackChanged`

This doesn't make a lot of sense: I can change it if it causes you problems.

**Comment by eoware** [comment]
No, this should work, the events will trigger different updates for my monitoring app, I just wanted to make sure I'd get something to let me know what was currently playing on startup without having to poll (which isn't feasible for my monitoring app). I have another unrelated question/possible issue I'll start on another thread.

**Comment by devgianlu** [comment]
Feel free to ask here if you want me to implement more events.

**Comment by devgianlu** [comment]
I have changed the events order to:
- contextChanged
- trackChanged
- playbackResumed
