### ISSUE TITLE
Bug? Feature Request? Multiple instances?

### ISSUE THREAD

**Issue by eoware** [librespot-org/librespot-java#154]
Sorry this is so brief. I just spent 20 minutes writing a nice report and background explanation, but then a misclick cleared the whole thing. 

Is running multiple instances of librespot-java on a single device supported? Has anyone done it? I have a use case that is working with vanilla librespot that doesnt seem to be working with -java.

**Comment by devgianlu** [comment]
You should be able to run multiple instances. I don't see how this would be useful: on many Linux systems you can't even have two players running at the same time.

**Comment by eoware** [comment]
My attempts failed, as it seemed to only work with either the last or the first instance brought up. The only thing I saw in the code that might cause issues is the dealer websocket, but I have very little understanding how the spotify protocol works or how librespot implements it.

The goal isn't to have two playing at the same time, it's to have the device 'appear' to be multiple different devices. I have a monitoring app that detects starts and stops from the librespot instances that turns on and off speaker zones based on which connect 'device' is played to. The zones are grouped and user-specific, so if they switch connect 'devices', spotify automatically stops the one and starts the other which sends the events I need. It's the most straightforward way I could figure out how to make user control of zones as simple as possible without needing a physical device per zone. I looked at Snapcast, etc. but this was the best I could come up with.

 An 'appear as multiple devices' feature would be ideal, but I understand my use case is pretty niche.

**Comment by devgianlu** [comment]
Make sure to change each instance name with `--deviceName`. You also have to disable cache or set a different location for each one. Everything else should be fine as is.

**Comment by eoware** [comment]
Yeah, I was definitely using different --deviceName's but maybe it was the cache that was causing me issues, thanks! I'd much rather use librespot-java for this for the websocket events alone. That does make me wonder, though, how would the websockets work with multiple instances?

**Comment by devgianlu** [comment]
I've just pushed cc25d64564a49cdd92f62fd38c9641026a480b00 so that you can assign a different port to each instance with `--api.port`.

**Comment by devgianlu** [comment]
@eoware Did you manage to run multiple instances?
