### ISSUE TITLE
Instance becomes unreachable with SocketException

### ISSUE THREAD

**Issue by Kucheek** [librespot-org/librespot-java#156]
**Describe the bug**

Seems the current version does not handle SocketExceptions as fine as it did before (I recollect it was very stable some time around commit 602c4e1 when we had been dealing with issue #134). Recently I run into some cases when it went unreachable for good and I had to restart:

_Case no.1_ - playback was running fine, Android client appeared as connected to librespot-java, I wanted to play different content, but librespot-java did not react on Android client commands, I had to restart librespot-java

_Case no.2_ - librespot-java has been idle for 2.5 hours since I paused playback and put Android client into airplane mode, it was unreachable when I woke up in the morning

**To Reproduce**
See above.

**Expected behavior**
SocketExceptions are handled correctly using reconnection logic, instance remains available.

**Screenshots/Stracktraces/Logs**
File with related log entries is attached: [librespot-java.log](https://github.com/librespot-org/librespot-java/files/3928121/librespot-java.log)

**Version/Commit**
Commit 255554b

**Comment by devgianlu** [comment]
That's an issue that I am investigating continuosly, I keep an instance running all the time and have a look at the logs everytime it disappears.

What I usually see is that the reconnection is handled fine, but the client isn't dispatched correctly. At some point, I'll need to capture some packets of the original client doing its stuff because I think it's an API issue.

**Comment by Kucheek** [comment]
Ok, thanks, I wasn't sure if it's just me having these problems. Overall, the connection provided by my current ISP is not very stable, frequent restarts, network infrastructure down every time. At least I am able to test this issue without much effort.
