### ISSUE TITLE
backend pipe unusable

### ISSUE THREAD

**Issue by praul** [librespot-org/librespot-java#157]
Hi there, thanks for your work

**Describe the bug**

- librespot java on backend pipe is dumping the whole track to pipe file - there is no real playback, controls are unusable therefore

- volume control is useless on pipe

**To Reproduce**

- set librespot to backend pipe, control it over spotify connect, listen to pipe file while trying to skip tracks

- try changing the volume on pipe

**Expected behavior**

- librespot only dumps small parts of track (like 2seconds) to pipe file. it remains controllable

- librespot handles volume while creating pipe stream (rust version does that)

**Version/Commit**
release 1.0.0 librespot-core-jar-with-dependencies.jar

I also tried STDOUT, but there was no audio on STDOUT, maybe I did something wrong
Thank you for any assistance

**Comment by devgianlu** [comment]
How are you playing the audio from the pipe?

**Comment by praul** [comment]
mainly with snapcast (https://github.com/badaix/snapcast) but behaviour is the same, if I don't play pipe at all

**Comment by praul** [comment]
It works just fine when the pipe is created with mkfifo, sorry for bother - was my mistake.
Volume control with pipe would be great though. Thank you

**Comment by devgianlu** [comment]
I thought volume control was already implemented. I'll test it.

**Comment by praul** [comment]
> I thought volume control was already implemented. I'll test it.

It's working, so.. nevermind.
I had all kinds of strange behaviour, when I created the pipe with 'touch'. With 'mkfifo' everything is working as it should. 
The java client is running way more stable than the rust implementation, also - no compiling needed. Thanks for that!

**Comment by devgianlu** [comment]
> I had all kinds of strange behaviour, when I created the pipe with 'touch'. With 'mkfifo' everything is working as it should.

I should probably document this somewhere because it relies on the buffer size of the pipe.
