### ISSUE TITLE
[Enhancement] Disable logging for embedded devices

### ISSUE THREAD

**Issue by Iscle** [librespot-org/librespot-java#159]
I'm planning to use this on an embedded device. However, I've noticed that there's a ton of logging about everything that's going on.

Maybe a toggle in the configuration file could be added to enable or disable logs.
As far as I know, printing text to the console or to a text file is quite expensive (especially in Java), so embedded devices with low power CPUs, would benefit from having this disabled once everything is set up.

Thanks for the hard work ;)

**Comment by devgianlu** [comment]
You can disable logging from the `log4j.properties` file situated inside `core/main/resources`.

**Comment by Iscle** [comment]
Oh, that's cool! 
I didn't know that... Never worked with log4j.

I'll do that.

Thanks,
Iscle
