### ISSUE TITLE
Need help getting zeroconf working

### ISSUE THREAD

**Issue by gcanzalo** [librespot-org/librespot-java#160]
Using an Orange Pi Zero as a spotify device. Cannot get the rustc version to compile on it. The java version works great as long as strategy="USER_PASS". When using ZEROCONF, device never shows in the spotify client. Sorry if this is an idiot question.

**Comment by devgianlu** [comment]
Could you post a log?

**Comment by gcanzalo** [comment]
Sorry I'm an idiot - where might I find the log?

**Comment by devgianlu** [comment]
The log file is basically the output of the program if run from the command
line.

**Comment by gcanzalo** [comment]
Well, now it works, so I guess no need to post the log! I don't get it. Screwed around with it all night when I first installed it and it wouldn't work. Now it does. Sorry to bug you.
