### ISSUE TITLE
Spotify connect session dosent end properly

### ISSUE THREAD

**Issue by Willyarma** [librespot-org/librespot-java#165]
When using spotify connect from my phone, playing via librespot-java (1.1.0 and 1.0.0) it works and also play / pause controls work but when I change back to play on my phone it seems that it dosent disconnect properly and the phone app wont play or pause.

I have tried it on 2 different computers and with 2 different phones.

**Comment by devgianlu** [comment]
I've noticed that too, initially I thought it was an issue with their client, but then realised it was probably librespot.

**Comment by Willyarma** [comment]
It works correctly in the rust version of librespot, but I want to use the HTTP POST control features of this version for play / pause / skip control.

**Comment by devgianlu** [comment]
I am not able to reproduce this anymore. Could you provide some detailed info?

**Comment by Willyarma** [comment]
I cannot pause by phone playing after using librespot-java, even if I kill the app as soon as it loads it starts playing again. The only way to fix it is to connect to another spotify connect server, like the web player.
When ever I press pause whilst playing on phone, a LOT of information scrolls up the console window from librespot.
I don't think it matters whether the music is playing or not when you switch back to phone.
I built from source today and the problem is the same.
I'm using an android phone and running librespot on Windows 10.

**Comment by devgianlu** [comment]
Is it fixed if you pull and recompile now?

**Comment by Willyarma** [comment]
Just given it a quick try and it seems to be working.
Thanks
