### ISSUE TITLE
Please can the websockets feature be altered so it available at all times

### ISSUE THREAD

**Issue by Willyarma** [librespot-org/librespot-java#166]
The websockets feature is something that I like very much, however the websockets port is only available AFTER a spotify connect device connects and is closed and re-opened when a new device connects. Can it be altered so that its always available and can also notify when a device connects and disconnects? (I would like to turn on and off an audio amplifier automatically)

**Comment by Willyarma** [comment]
Alternatively running an external command on play/ stop events like the rust version does would be OK.

**Comment by devgianlu** [comment]
I thought this would be a simple process, but it takes more effort than I expected. I might as well create a PR.

**Comment by devgianlu** [comment]
With the latest commit I have added three endpoints:
- `sessionCleared`, when the current session is closed
- `sessionChanged`, when the current session is changed with a new one
- `inactiveSession`, when the current session becomes inactive (no sound until `playbackResumed`)

The API is also available on startup.

**Comment by Willyarma** [comment]
That was quick, thank you very much! I've just given it quick try and it looks good.

**Comment by devgianlu** [comment]
You can close the issue when you're sure everything is working fine.
