### ISSUE TITLE
improve: using protobuf maven plugin 

### ISSUE THREAD

**Issue by STRRL** [librespot-org/librespot-java#170]
I have seen here are some generated-class like `xyz.gianlu.librespot.common.proto.Authentication` generated by protoc.

It's a best practice to using maven plugin to generate this file during maven compile phase.

Such as [xolstice/protobuf-maven-plugin](https://github.com/xolstice/protobuf-maven-plugin),  suggested by grpc-java.

It could reduce thousands of line of code for easier maintenance. (also improve my IDE indexing performance

**Comment by devgianlu** [comment]
Good point, I was planning to add the proto definitions separately, but this seems to be the best solution.

**Comment by devgianlu** [comment]
> 1,164 additions and 151,321 deletions.
