### ISSUE TITLE
Is there an option to set log level?

### ISSUE THREAD

**Issue by Willyarma** [librespot-org/librespot-java#171]
Not important, but I was wondering if there was an option to set the log level?
Thanks for all your hard work on this amazing software.

**Comment by devgianlu** [comment]
See https://github.com/librespot-org/librespot-java/issues/159.

Some examples: https://docs.oracle.com/cd/E29578_01/webhelp/cas_webcrawler/src/cwcg_config_log4j_file.html

**Comment by IiroP** [comment]
Could this be added as option (to config file) so there would be no need to build the project from source after every update?

**Comment by devgianlu** [comment]
> Could this be added as option (to config file) so there would be no need to build the project from source after every update?

Done!
