### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by sirlenni** [librespot-org/librespot-java#172]
**Is your feature request related to a problem? Please describe.**
My company blocks any outgoing requests not made through their https proxy.

**Describe the solution you'd like**
Allow a toggeld setting in the config that allows me to input IP,Port and auth info for a https proxy.

**Describe alternatives you've considered**
I have tried different proxy tunneling apps as well as running the java container with parameters to connect to the proxy, which works but doesn't alllow me to interact with the API any longer since the API Server is also going into the proxy.

**Comment by devgianlu** [comment]
I have added support for proxies on `dev`. Before being able to configure it you need to run the executable once, then you can edit the proxy settings under the `proxy` category.

Let me know if it works.

**Comment by Willyarma** [comment]
Looks like master was updated not dev

**Comment by devgianlu** [comment]
> Looks like master was updated not dev

My fault, I've updated `dev` too.

**Comment by sirlenni** [comment]
As of now everything seems to be working.
However if the proxy drops a packet it goes into reconnect mode which is not an issue in itself.
However the API also does not respond while the timer is counting down for reconnect.
Otherwise working perfect, Thank you so much.

**Comment by devgianlu** [comment]
> However the API also does not respond while the timer is counting down for reconnect.

I should probably add an event to the websocket API to signal the status of the server connection. 

What happens exactly when you send requests during the reconnection timeout? We should send something like 503 and set an appropriate `Retry-After` header.

**Comment by devgianlu** [comment]
I've made said changes to `dev`. Let me know

**Comment by sirlenni** [comment]
In the version I had compiled it would simply drop the requst made to API while reconnecting to proxy
I will compile the newest dev and report back later

**Comment by Shinoby92** [comment]
can it be that proxy does not work with authentication enabled?
means config.toml

`[proxy] ### Proxy ###
enabled = true # Whether the proxy is enabled
type = "HTTP" # The proxy type (HTTP, SOCKS)
address = "123.123.123.123" # The proxy hostname
port = 1234 # The proxy port
auth = true # Whether authentication is enabled on the server
username = "user123" # Basic auth username
password = "pass123" # Basic auth password`

proxy does work, but not when auth set to true and username+password set like above

**Comment by devgianlu** [comment]
@Shinoby92 Seems unlikely, the only problem I can see is the server having issues with HTTP 1.0 since I've hardcoded the version.

**Comment by Shinoby92** [comment]
I tried now:
proxy false -> librespot working
proxy true authentification=false (auth with my ip address)  -> librespot working
proxy true authentification=true (with username & password)  -> librespot not working

I tried simple requests and other stuff with authentification username+password and it does work everywhere else only librespot does not work when using proxy with username & password authentification.
so im pretty sure its not proxy or system based, there is something not working with authentification. How can i check out if the proxy uses some hardcoded "must use" http 2.0 or what ever seems like there's a conflict then, if you can get it work with auth, then it has to be maybe the http version that's not working with my proxy used

**Comment by devgianlu** [comment]
Try editing this line: https://github.com/librespot-org/librespot-java/blob/f69d3ed7992069eca345a5da89ad414d1d5dfac3/lib/src/main/java/xyz/gianlu/librespot/core/Session.java#L1231

It that's not the problem, please open a new issue.

**Comment by Shinoby92** [comment]
fixed it and created a pull request
