### ISSUE TITLE
Add metadata pipe support

### ISSUE THREAD

**Issue by uvjustin** [librespot-org/librespot-java#174]
**Is your feature request related to a problem? Please describe.**
Complementary projects such as forked-daapd support receiving metadata in a pipe. Since this library already supports gathering all the metadata, marshalling the metadata into a separate pipe seems straightforward.

**Describe the solution you'd like**
Add metadata pipe support like in this commit in another (Rust) fork of librespot: https://github.com/billsq/librespot/commit/549faa88770c5f9ce87dbe1f11ef2765a48c66d1

**Describe alternatives you've considered**
Alternatively this can be implemented by the pipe reading side or through a separate daemon by using the API to subscribe to events, grab the metadata, and write the metadata to a pipe.

**Additional context**

**Comment by devgianlu** [comment]
That's pretty cool, could you point me to the documentation on how the data should be sent on the pipe?

**Comment by uvjustin** [comment]
Have a look here https://github.com/mikebrady/shairport-sync-metadata-reader

**Comment by devgianlu** [comment]
@uvjustin You can set the metadata pipe with the `player.metadataPipe` option. I was not able to make  it work with [shairport-sync-metadata-reader](https://github.com/mikebrady/shairport-sync-metadata-reader), but it looks fine to me. 

If it works for you, I can add more events.

**Comment by uvjustin** [comment]
Thanks, let me give it a try!

**Comment by uvjustin** [comment]
Just tried it with forked-daapd - the basic metadata seems to go through just fine. Great work.

**Comment by devgianlu** [comment]
@uvjustin Is there any other event that could be added to the pipe? I feel like some of them could be useful.

**Comment by uvjustin** [comment]
I'm using it with forked-daapd. In addition to the codes you have already added, forked-daapd supports:
"asgn" - Genre (doesn't seem to be listed on the shairport-sync-metadata-reader readme), but same implementation as album, artist, title
"prgr" - RTP timestamps for progress
"PICT" - png or jpg less than 262144 bytes

**Comment by devgianlu** [comment]
I could easily implement `asgn`, but I don't have any idea on how to do the other ones. I cannot find any good documentation.

**Comment by uvjustin** [comment]
Hi, see this PR https://github.com/librespot-org/librespot-java/pull/182
