### ISSUE TITLE
IllegalStateException: Session isn't authenticated if Session.close() is called manually

### ISSUE THREAD

**Issue by funtax** [librespot-org/librespot-java#176]
**Describe the bug**
If I call Session.close() the exception below occurs.
I assume this happens because the close()-implementation doesn't wait for the receiver-thread to finish:

```
         if (this.receiver != null) {
            this.receiver.stop();

// maybe we have to wait until this.receiver has finished before continue

            this.receiver = null;
        }
        if (this.dealer != null) {
            this.dealer.close();
            this.dealer = null;
        }
```

**To Reproduce**
Call Session.close() manually, right now it's just called within ShutdownHook.

**Expected behavior**
The session closes without exception.

**Screenshots/Stracktraces/Logs**
java.lang.IllegalStateException: Session isn't authenticated!
        at xyz.gianlu.librespot.core.Session.mercury(Session.java:439)
        at xyz.gianlu.librespot.core.Session$Receiver.run(Session.java:989)
        at java.lang.Thread.run(Thread.java:919)

**Version/Commit**
Current stable release.

**Comment by funtax** [comment]
Nevermind, seems to be a conflict with my current situation where I manually closed the session once the network disappears. The receiver has been re-introduced by the reconnect-feature :)

**Comment by devgianlu** [comment]
> I assume this happens because the close()-implementation doesn't wait for the receiver-thread to finish

That's actually correct and I was going to implement it, but we don't know when the thread will exit because it is waiting on a network task (receiving a TCP packet). It will probably exit when ` conn.socket.close();` is called.
