### ISSUE TITLE
Provide current dev-builds via maven

### ISSUE THREAD

**Issue by funtax** [librespot-org/librespot-java#181]
Hey @devgianlu ,

I do really enjoy your very hard work on this project and am watching the progress since beginning.
Do you think it's possible to create a task that automatically pushes your new commits to maven central so it's not required to compile each new commit manually but just update the maven dependencies?

Don't know if this is easily possible, but maybe you know a way :)

**Comment by devgianlu** [comment]
I have published the first snapshot for librespot (https://travis-ci.com/librespot-org/librespot-java/builds/152322643): `xyz.gianlu.librespot:librespot-core:1.3.0-SNAPHOST`

**Comment by funtax** [comment]
Thank you very much @devgianlu !
