### ISSUE TITLE
Question: What is the minimum targeted JRE 8 or 11 ?

### ISSUE THREAD

**Issue by lkwg82** [librespot-org/librespot-java#193]
The explicit statement makes it clearer for refactorings.

I favor of course the latest LTS 11 ;)

What is ur opinion on that?

**Comment by devgianlu** [comment]
The current minimum for compiling is JDK 8. I don't really know the benefits of increasing to 11 over 8, but still I'm compiling and developing with 11 (the releases also use that).

**Comment by lkwg82** [comment]
There are a lot of improvements:
 https://codete.com/blog/java-8-java-11-quick-guide/

I would recommend hava 11 if we can allow leave compatibility of java 8.

**Comment by devgianlu** [comment]
I did a quick Google search and apparently missed all this stuff. Yeah, the improvements are nice, but how could I keep compatibility with Java 8 if it is compiled by Maven with Java 11?

**Comment by lkwg82** [comment]
You are safe. It works like it is configured now.

But what is the benefit of java8 compatibility?

Because compatibility is always kind of burden.

**Comment by devgianlu** [comment]
> But what is the benefit of java8 compatibility?

I feel like many people may still be using Java 8. We could maybe start the refactoring process for Java 11 on a different branch and then when it will eventually be done, move to it. Doing so right now feels pretty useless as I don't use any feature of it.

**Comment by lkwg82** [comment]
You know then u will have to maintain two branches.

When is EOL of java8?

**Comment by lkwg82** [comment]
Java 8 is already EOL for public updates. Everything else are paid update channels.

See: https://www.oracle.com/java/technologies/java-se-support-roadmap.html

**Comment by devgianlu** [comment]
> You know then u will have to maintain two branches.

The development is going pretty slow now therefore I don't think it'll be a big issue. I just think it's pointless to update to Java 11 if we are not using any feature of it, but I'll happily do it once we use it to improve the project.

**Comment by lkwg82** [comment]
IMHO improvements are done slowly with no big bang, else they are never done ;).

From my point this question is answered.

**Comment by Kucheek** [comment]
For future reference, please keep in mind that moving to Java 11 would make librespot-java incompatible with clients having armv6 architecture (RPi 0, RPi 1) where only Java 8 is available.
