### ISSUE TITLE
reset pipe file keep it empty

### ISSUE THREAD

**Issue by 3l0w** [librespot-org/librespot-java#194]
**Describe the bug**
while librespot api is running, i clear the file (in this case : rm file.raw; touch file.raw).
i can change the song playing but the file remains empty.

**To Reproduce**
execute librespot-api-jar-with-dependencies.jar with pipe option enabled with name file: file.raw
pause the playing (dont know if this is a must)
rm file.raw; touch file.raw
change the song from spotify or with the api

**Expected behavior**
In this case the file should continue to get fill.

**Version/Commit**
https://github.com/librespot-org/librespot-java/commit/4784a5c85e2d7e8761e81f72e46531bc3619f76d

**Comment by devgianlu** [comment]
Once the file descriptor has been acquired, the file cannot be changed. Since this looks to me like a feature to allow piracy I'm closing this.
