### ISSUE TITLE
Gapless playback not working on latest dev code

### ISSUE THREAD

**Issue by josephcarroll** [librespot-org/librespot-java#197]
**Describe the bug**
There is a very noticeable gap of 0.2 to 1 second between tracks when playing Spotify music through librespot-java. I checked out the code and see two potential sources of the problem. 1. we call `state.updated()` before `trackHandler.pushToMixer(reason)` when about to play the next preloaded track. This invokes a network call that can take a long time to run. 2. we call `trackHandler.seek(state.getPosition())` somewhat pointlessly when crossfading is not enabled. 

**To Reproduce**
Check out latest dev code on OS X, run librespot-java with no config changes (e.g. Zeroconf and no crossfade), then play something gapless. Examples tested - Dark Side of the Moon and Plastic Beach.

**Expected behavior**
I expect to hear 0 gaps between the first and second tracks of the two example albums.

**Comment by josephcarroll** [comment]
ok - and `trackHandler.seek` is causing a delay because it's again invoking `state.updated()`. Should we look at running these updates in a separate thread to avoid blocking the actual audio?

**Comment by devgianlu** [comment]
This is an issue I've been putting aside for a while, but I guess it is time to move the state update calls to another thread. It is important to keep them in order so a queue is the more appropriate method. Will work on it.

**Comment by josephcarroll** [comment]
Actually, if you give me a few days I would be happy to submit a PR! As long as you can reproduce and agree it’s a problem with gapless playback.

**Comment by devgianlu** [comment]
Even if I've never experienced it, I agree it is an issue.

**Comment by devgianlu** [comment]
@josephcarroll Network requests are now being made on separate thread. You can test it on `dev`, let me know how it goes.

**Comment by josephcarroll** [comment]
It’s almost perfect now. I think there is an issue around the next track being seeked a couple of milliseconds - but we should track it separately.
