### ISSUE TITLE
normalisationPregain values

### ISSUE THREAD

**Issue by ikirmitz** [librespot-org/librespot-java#199]
Hello and apologies in advance if this the wrong place to ask this question. 

Spotify client has 3 different levels of normalisation: Quiet, Normal and Loud
I have noticed that the Normal setting in the spotify client is significantly louder than the default normalisationPregain (0.0) value in config.toml
Can you please provide a mapping of the spotify client settings to the correct normalisationPregain values?
ie 
quite: -10.0
normal: 5.0
loud: 10.0

Many thanks in advance

**Comment by devgianlu** [comment]
From the Spotify artists' page ([here](https://artists.spotify.com/faq/mastering-and-loudness#can-users-adjust-the-levels-of-my-music)):
> Loud - equalling ca -11 dB LUFS (+6 dB gain multiplied to ReplayGain)
Normal (default) - equalling ca -14 dB LUFS (+3 dB gain multiplied to ReplayGain)
Quiet - equalling ca - 23 dB LUFS (-5 dB gain multiplied to ReplayGain)

Using a pregain of 3dB seems to make the loudness level equal. I should probably change the default to +3dB.

**Comment by ikirmitz** [comment]
Thank you, that is great!

**Comment by ikirmitz** [comment]
It would also be great if you can add the above as a comment in the config.toml or in the REAME.
Thanks

**Comment by devgianlu** [comment]
I've added a comment to the configuration file.
