### ISSUE TITLE
Add explicit filter option

### ISSUE THREAD

**Issue by ikirmitz** [librespot-org/librespot-java#200]
**Is your feature request related to a problem? Please describe.**
Spotify has the option to prevent playback of explicit content which is essential for family listening

**Describe the solution you'd like**
Enable support of explicit content filtering in librespot-java, ideally something that can be toggled from the native spotify client. RIght now when you select librespot-java as the output device and try to toggle the filter you get an error in the client.

**Comment by devgianlu** [comment]
`librespot-java` now synchronizes with the settings of the client. You can try the latest commit on `dev`.

**Comment by ikirmitz** [comment]
Oh mate you're a legend. Does the dev also include the api functionality??
it looks like it

**Comment by devgianlu** [comment]
> Does the dev also include the api functionality??

Everything you need is on `dev` or you can use `master` for the latest stable release.

**Comment by jscholes** [comment]
@devgianlu Apologies for chiming in on a closed thread; this is awesome and I had a couple of quick questions:

1. Where do you source the protobuf files for Spotify?  Can they somehow be extracted from Spotify clients?
2. How do you check for changes used by Spotify's official apps so you can implement them into this project?

Thanks!

**Comment by jscholes** [comment]
Oh, one more thing: where do you source the Hermes "hm://" URIs for various services?  Shout if you'd rather I ask these somewhere else.

**Comment by devgianlu** [comment]
> Where do you source the protobuf files for Spotify? Can they somehow be extracted from Spotify clients?

All the protobuf definitions come from the executables and are extracted with [this script](https://github.com/HearthSim/proto-extractor/blob/master/protobin_to_proto.py).

> How do you check for changes used by Spotify's official apps so you can implement them into this project?

Usually, they don't make breaking changes therefore as long as we keep the version number stable nothing will stop working. The main reason to start making changes in the code is to keep it in line with the original client and implement new features.

> where do you source the Hermes "hm://" URIs for various services?

We used to have a tool set with some [custom scripts](https://github.com/librespot-org/spotify-analyze) that dump all the requests made by the client, but it stopped working recently and I can't fix it myself (for now), you can still use it on Ubuntu with some older versions.

> Shout if you'd rather I ask these somewhere else.

If you have any other question regarding this project specifically you can open a new issue here or if you have general questions on the topic you can message me on Gitter.
