### ISSUE TITLE
Bug with TimeProvider (PING)

### ISSUE THREAD

**Issue by funtax** [librespot-org/librespot-java#202]
**Describe the bug**
I think there's a bug within the TimeProvider.updateWithPing().

I assume it's missing an "L" and casting wrong:

Corrent: long diff = ByteBuffer.wrap(pingPayload).getInt() * 1000L - System.currentTimeMillis();

instead of 

Wrong: long diff = ByteBuffer.wrap(pingPayload).getInt() * 1000 - System.currentTimeMillis();

**Comment by devgianlu** [comment]
You are right, I fixed that.
