### ISSUE TITLE
Terms and Conditions - Risk of getting my account disabled?

### ISSUE THREAD

**Issue by Code42Cate** [librespot-org/librespot-java#211]
Hey there, 

I love this project and would like to use it on my Raspberry Pi and contribute if possible. Does anyone know if this is compliant with the Spotify Terms and Conditions? Would like to not get my account disabled or do something illegal:D

Cheers

**Comment by devgianlu** [comment]
Both librespot (5 years) and librespot-java (1,5 years) are now pretty old and I can tell you that nobody ever got his account disabled. I'm not into legal stuff so I can't tell you if we're doing something illegal, none ever contacted me regarding this. 

You surely could get in trouble in trying to pirate music and stuff which we **DO NOT** encourage. Also remember that we support only premium accounts and don't have to deal with ads and playback limitations (audio quality, max number of skip, etc).
