### ISSUE TITLE
Time/Position is wrong after "pause"

### ISSUE THREAD

**Issue by funtax** [librespot-org/librespot-java#213]
If you are listening to a song (playing), press pause, then wait several seconds and press play again.
The position shown inside Spotify is now wrong.
It seems like it continues the position-timer in the background.

Maybe this issue has been introduced by #175 ?

I have a private Java-implementation of librespot and in my project I am sending the current position reported by the Vorbis-decoder once the playback-state changes, and additionally frequently during playback to force the Spotify-client and the local client to be in-sync.

In librespot-java, it's done eg. here and I think it's not working well:

Player.playbackResumedFromHalt():
state.setPosition(state.getPosition() - diff);

Maybe it's possible to either fix this, or use "player.getPosition" if possible and only use above code if player.getPosition() returns null in case of episodes.

And eventually it's possible to send position-updates frequently each x seconds for a better synchronization with the client?

**Comment by devgianlu** [comment]
I am in the process of rewriting the player to accommodate the metrics required for #155, I'll keep this issue open. The issue will probably reappear.

**Comment by josephcarroll** [comment]
Just as an FYI - I can replicate the issue consistently.

**Comment by funtax** [comment]
This issue is still open with the latest version (#155 merged into dev).

**Comment by devgianlu** [comment]
I know, I wanted to merge it because the player code changed quite a lot. Will take a look at this next.

**Comment by funtax** [comment]
Yes of course, no worries. The latest version runs right now pretty well on my device (right now) :)

**Comment by devgianlu** [comment]
This should now be fixed, perhaps not in the way Spotify intended, but it works.

**Comment by funtax** [comment]
Works, thank you very much :)
