### ISSUE TITLE
Zeroconf throws after connection has been lost and reconnected

### ISSUE THREAD

**Issue by Iscle** [librespot-org/librespot-java#218]
This happened while testing the latest build for the other issue (#216).

I have a USB-C to Gigabit ethernet adapter. Sometimes, the USB controller fails, and the adapter gets disconnected and connected back again, just like if I had unplugged it and plugged it back. This is not a problem for me, but it seems that librespot-java didn't like it.

I wasn't playing music during that time, but then, I noticed that Zeroconf started throwing "NoRouteToHostException" exceptions. I tried to play one song with librespot, using the Windows Spotify client using Zeroconf, and after a while it worked. Then, the song finished and nothing else played. In the meanwhile, more exceptions were being thrown.

This is the log, from good, known state of the execution (before the disconnect), to the end. The error ocurred at timestamp "2020-04-29 14:48:50,677".
https://del.dog/fucomisiri
This is an screenshot of how the client looks after the song finished:
https://prnt.sc/s808ev

**Comment by devgianlu** [comment]
There seem to be an issue with [devgianlu/zeroconf-java](http://github.com/devgianlu/zeroconf-java), in addition to #216.

**Comment by devgianlu** [comment]
Since the `NoRouteToHostException`s aren't causing any issue (are being caught), I think this is pretty much the same issue of #216. 

The exceptions being thrown by zeroconf-java also seem to be related to firewall issues, maybe the adapter hadn't finished starting up? I tried unplugging the Ethernet cable while it was running and nothing happened.

**Comment by Iscle** [comment]
Hi! Sorry for the delay on the answer. 

Removing the ethernet cable and plugging it back in won't reproduce this issue. What disconnected in my case was the entire network adapter, which was plugged in via USB. I guess that caused a change in the enumeration of the device or something, which ZeroConf couldn't recover from.

I took a look at the ZeroConf code and I couldn't see an obvious way of fixing this issue. That said, this is an edge case. Most people are not using removable network cards...
