### ISSUE TITLE
Retrieve queued items

### ISSUE THREAD

**Issue by chalkyjoe** [librespot-org/librespot-java#222]
Would it be possible to retrieve your Spotify queue via the API? Preferably with all metadata of each song :). Would be super useful to be able to pre-load any future cover art. 

The ability to manipulate the queue (add/remove) would also be awesome!

Love the library, extremely handy and something I've dreamed of having since getting my first Raspberry Pi!

**Comment by devgianlu** [comment]
I've made some changes to `dev`, the `/player/tracks?withQueue=<true/false>` is now available.

**Comment by devgianlu** [comment]
I've added the add/remove operations, let me know if it works.
