### ISSUE TITLE
Can't send audio to BT headphones

### ISSUE THREAD

**Issue by pnpires** [librespot-org/librespot-java#224]
This is probably not a bug, but I can't send audio to my BT phones.

I'm using librespot-java through spocon, and it works great. But I have a BT headphones paired and working with all other system sound (youtube, etc.) 

But audio from spocon refuses to obey my system choice. Always goes through system speakers. 

By spocon dev suggestion I installed lovspotify because it lists devices and allows to choose one in the front end. I see several Alsa devices there, but none of it seems to make any difference. 

What am I doing wrong? Thanks for your help

**Comment by devgianlu** [comment]
I think maybe this question is better suited for [spocon/lovspotify](https://github.com/spocon/lovspotify). @spocon

**Comment by spocon** [comment]
I just pointed him to you because I thought you are better in this 🤣

**Comment by pnpires** [comment]
I came here by spocon/lovspotify dev suggestion. Maybe you could have some help on the audio pathway. 
What is librespot-java behavior with bluetooth? Shouldn't be an issue and behave accordingly system mixer setting?

**Comment by spocon** [comment]
raspotify is a project which has the same stack as librespot-java , they use also librespot.... 
people there have the same issues. One guy seemed to figure it out:
https://github.com/dtcooper/raspotify/issues/63

**Comment by spocon** [comment]
This guy have to figured it out as well 

https://github.com/bablokb/pi-btaudio

**Comment by devgianlu** [comment]
Looks like a configuration issue.

**Comment by pnpires** [comment]
Thanks for your help. I saw the solutions pointed out. I'm not going to pursuit it because I need something more usable. Right now I have spocon sending sound via HDMI to my AV/AMP. That would be its main use. Passing audio from BT to my headphones via Pi is redundant at my setup. I can always pair my headphones with my phone or laptot. 

I understand this solution is a must for people that has BT speakers as its main audio source. 

I just didn't understand why librespot/spocon/lovpotify weren't obeying the system mixer setting, and most probably that could be some setting that a newbie like me was missing. Also my image is a Kali, not a Raspbian, so that is another layer that could complicate things a bit.

In case of absolute need I guess it's easier to pair my headphones with other source, than change a config file and reboot the service.

Thanks for your help and great work!
