### ISSUE TITLE
StackOverflowError while connecting

### ISSUE THREAD

**Issue by Kucheek** [librespot-org/librespot-java#236]
**Describe the bug**
Could not establish connection to librespot-java after some idle time (around 20 hours). Tried twice, 15:01:22 and 15:02:50, StackOverflowError appeared each time.

**Screenshots/Stracktraces/Logs**
https://del.dog/loderricro

**Version/Commit**
commit c34d20e

**Comment by devgianlu** [comment]
I fixed a similar issue with 08282b94d6adc7e5e5a07fe20c150829fc912943. Fixing this should be simple.
