### ISSUE TITLE
ApiClient:105 - PUT https://guc-spclient.spotify.com/connect-state/v1/devices/... returned 413

### ISSUE THREAD

**Issue by SuperCreedy** [librespot-org/librespot-java#239]
**Describe the bug**
The call to the Spotify Connect status API fails if you are listening to a playlist (or your library / liked songs) with ~1500 songs or more.

**To Reproduce**
Create a large playlist 😁, play back using librespot-java.
Inspect the JSON payload sent to the API. The next_tracks element is repeated many times (in my case thousands of times).
I'm guessing this pushes the request size over the limit on the API gateway on Spotify's side.
Sorry, I don't have much Java programming experience so I got stuck at this point...

**Expected behavior**
The current track and seek position should be reflected in the official client devices e.g. desktop client and the Android app.

**Screenshots/Stracktraces/Logs**
`
2020-06-24 19:11:10,427 WARN  ApiClient:105 - PUT https://guc-spclient.spotify.com/connect-state/v1/devices/... returned 413. {headers: content-length: 0
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
date: Wed, 24 Jun 2020 18:11:09 GMT
server: envoy
via: HTTP/2 edgeproxy, 1.1 google
alt-svc: clear
}
`

**Version/Commit**
Dev branch as of today.

Thanks!

**Comment by devgianlu** [comment]
Should cause no problem now. I've limited the previous tracks to 16 and next tracks to 48.

**Comment by SuperCreedy** [comment]
I've tested this and it resolved my issue, thanks so much! 😊
