### ISSUE TITLE
Can't run librespot-java

### ISSUE THREAD

**Issue by lukilukeskywalker** [librespot-org/librespot-java#24]

**Comment by lukilukeskywalker** [comment]
I am not a programer, and might be doing something wrong, but as I try to load the proyect (as it is, and i mean, I download all files, and just add it as a proyect to eclipse) and then try to run the main class in /src/main/java/org/librespot/spotify, to test it out, the compiler fails and says "Could not find or load main class" 
I have tried a few things, from moving the files around, putting them in the src folder, with package "default package" to setting a new build path, just to make sure it knows where the main class is
Am I overseeing something? I dont understand why it cant find the main class

**Comment by devgianlu** [comment]
I've made this with IntelliJ IDEA and it therefore mixes some Maven and
some standard Java stuff. I'll refactor it a little bit so that it can be
used with Maven only. I should also list the commands to run it in the
README.

**Comment by devgianlu** [comment]
Everything should be OK now. Reopen the issue if you still can't compile.
