### ISSUE TITLE
Authentication blob generation

### ISSUE THREAD

**Issue by Njitram2000** [librespot-org/librespot-java#242]
Maybe I completely missed it but there is no documentation on how to generate the authentication blob. This is the first time I would be using a blob so maybe I'm missing something obvious but looking at the code that decrypts it from the config, I would have to write my own program to generate it based on your code.

**Comment by devgianlu** [comment]
TBH, I've never used this feature. Authentication blobs are created directly by Spotify servers. If you want to save credentials to reuse them then you are probably looking at stored credentials.

**Comment by Njitram2000** [comment]
Ah, I see. From the way you worded "having hardcoded passwords isn't the best thing on earth" I assumed the blob was the recommended way to authenticate.
I have no idea if it's possible but if Spotify returns a refresh token, you could send the credentials once via REST instead of the toml file and then store the token instead.
Is the authentication system something you wrote or part of the port from rust? Otherwise I'll attempt to dig into the code myself.

**Comment by devgianlu** [comment]
I've ported the authentication too. The recommend way is to login once with credentials and then reuse the stored ones (this way you won't receive a login email everytime too). I should probably specify this on the README.

**Comment by Njitram2000** [comment]
You say login once and then reuse but both the first login and the subsequent logins are read from the toml file, aren't they? Or is there a separate authentication store that I haven't seen? So basically, add login and password to the toml file and leave them there.

**Comment by devgianlu** [comment]
There is a separate authentication file that is created for stored credentials. Keeping the credentials in the toml file isn't very good as it leaves a plaintext password which is probably used on other accounts too.

https://github.com/librespot-org/librespot-java/blob/427d995b98842bff5c32deae10d823837cce884f/core/src/main/java/xyz/gianlu/librespot/core/Session.java#L967

https://github.com/librespot-org/librespot-java/blob/427d995b98842bff5c32deae10d823837cce884f/core/src/main/java/xyz/gianlu/librespot/core/Session.java#L408

**Comment by Njitram2000** [comment]
Perfect, that's exactly the problem I was trying to solve.
I have created a PR to clarify this for anyone else wondering about it: https://github.com/librespot-org/librespot-java/pull/243
Thank you for your work on this!
