### ISSUE TITLE
Better error handling after zeroconf issues (and a request for help to debug the issue)

### ISSUE THREAD

**Issue by l3d00m** [librespot-org/librespot-java#247]
**Describe the bug**
I'm experiencing issues with librespot-java zeroconf discovery, but only on one specific client, which is a raspberry 3 with a fresh raspbian install (but it also has pihole, homeasssistant and some other stuff installed on it which might interfere). Another Pi with the exact same version of librespot-java runs just fine, but this one raspberry is simply not showing up in spotify's list of devices.

This is similar to #246, but a zeroconf `/?action=getInfo` GET request returns the same on both clients (except device ID and public key) , so it seems like a client-specific issue that the broken client never makes itself public for the Spotify clients. 

As you can see in the below logs, the start of librespot-java is stalled after " Zeroconf HTTP server started successfully", whereas on the working raspberry it'll say "Zeroconf:473 - Announced Service" shortly after starting the server.

Because I have absolutely no experience with zeroconf I couldn't further debug the issue. Nevertheless I'd say that librespot-java should do some error handling when it fails to launch the zeroconf service properly.

**To Reproduce**
Not sure unfortunately, which is why I'm looking for a way on how to debug this.

**Expected behavior**
If there is an issue with the zeroconf discovery (announcement?) it should crash / show in the logs.

**Screenshots/Stracktraces/Logs**
Log level for both raspberrys is TRACE

Log from the **broken** raspberry (it's pretty short and nothing else will show up, even after a few minutes):
```
pi@raspi-server:~ $ java -jar librespot-player-1.5.1.jar
2020-08-10 23:32:41,309 INFO  Utils:84 - Cryptography restrictions removal not needed.
2020-08-10 23:32:41,438 INFO  ZeroconfServer:442 - Zeroconf HTTP server started successfully on port 21787!
```

In comparison, log from the **working** raspberry:
```
pi@raspi-zwei:~ $ java -jar librespot-player-1.5.1.jar
2020-08-10 23:32:54,607 INFO  Utils:84 - Cryptography restrictions removal not needed.
2020-08-10 23:32:54,926 INFO  ZeroconfServer:442 - Zeroconf HTTP server started successfully on port 17169!
2020-08-10 23:32:55,886 TRACE ZeroconfServer:506 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Connection=keep-alive, User-Agent=Spotify/113800558 Win32/0 (PC desktop), Host=192.168.0.107, Accept-Language=en, Accept-Encoding=gzip, deflate, Content-Type=application/x-www-form-urlencoded}
2020-08-10 23:32:56,527 INFO  Zeroconf:473 - Announced Service{alias='librespot-java', service='spotify-connect', port=17169, text={VERSION=1.0, CPath=/, Stack=SP}, addresses=[/192.168.0.107], domain='.local', protocol='tcp', host='raspi-thomas'}.
2020-08-10 23:34:34,851 TRACE ZeroconfServer:506 - Handling request: GET /?action=getInfo&version=2.7.1 HTTP/1.1, headers: {Connection=keep-alive, User-Agent=Spotify/113800558 Win32/0 (PC desktop), Host=192.168.0.107, Accept-Language=en, Accept-Encoding=gzip, deflate, Content-Type=application/x-www-form-urlencoded}
```

**Version/Commit**
tested with both librespot-api-1.5.1.jar and librespot-player-1.5.1.jar

**Comment by devgianlu** [comment]
It seems to get stuck somewhere in between the gathering of the network interfaces and the dispatching of the service. Try this:
```toml
[zeroconf]
	listenAll = false
	interfaces = "eth0"
	listenPort = -1
```

If you can hook up a debugger you could try stepping trough this: https://github.com/librespot-org/librespot-java/blob/0be6da0b6dd26c92d448bf4aa5a88bd3d97a6a6f/lib/src/main/java/xyz/gianlu/librespot/ZeroconfServer.java#L110-L144

**Comment by l3d00m** [comment]
Ah that was helpful, it indeed works if I specify a network,

FYI I'm using docker, so I have like 9 different network interfaces.

I attached a debugger and it's stuck at `zeroconf.addNetworkInterfaces(nics);`: https://github.com/librespot-org/librespot-java/blob/0be6da0b6dd26c92d448bf4aa5a88bd3d97a6a6f/lib/src/main/java/xyz/gianlu/librespot/ZeroconfServer.java#L135

I jumped into and it seems to iterate fine at `addNetworkInterface` inside `Zeroconf.java` for one time (first interface is some virtual eth from docker) but it'll get stuck the second time, which is also some veth. It'll stuck at this line: 
https://github.com/devgianlu/zeroconf-java/blob/master/src/main/java/xyz/gianlu/zeroconf/Zeroconf.java#L589

If I jump into the Java bytecode for `channel.register()` in that line, I land in a file called AbstractSelectableChannel, which seems to be throwing a `IllegalBlockingModeException` inside the function `public final SelectionKey register(Selector sel, int ops, Object att)`:
![grafik](https://user-images.githubusercontent.com/12055376/89953092-bd414880-dc2e-11ea-97f4-3b419d7cd2b2.png)


Then it somehow hangs, I hope this is of help for you.

**Comment by devgianlu** [comment]
What's the interface it blocks for?

**Comment by l3d00m** [comment]
This one (you can see below in the debug view)
![idea64_2020-08-11_23-57-48](https://user-images.githubusercontent.com/12055376/90021680-e2c36600-dcb1-11ea-929a-d1e5f82951aa.png)

**Comment by devgianlu** [comment]
> Google: ETH (virtual Ethernet)
> Java: `virtual = false`

Good job Java! lol

I guess the fix is to exclude this interface like every other virtual interface.

**Comment by devgianlu** [comment]
What's the MAC address of that interface?

**Comment by l3d00m** [comment]
Oh btw, the first nic it does **not** hang on is a `veth` with `virtual=false` as well, see: 

![image](https://user-images.githubusercontent.com/12055376/90061591-a100e280-dce6-11ea-8c16-419fc56fb765.png)

All macs and everything
```
pi@raspi-server:~ $ ifconfig -a
br-8179ea4a043c: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 172.18.255.255
        inet6 fe80::42:59ff:fe88:48c9  prefixlen 64  scopeid 0x20<link>
        ether 02:42:59:88:48:c9  txqueuelen 0  (Ethernet)
        RX packets 7389159  bytes 1346923827 (1.2 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9405739  bytes 770283820 (734.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:4dff:fe5d:d904  prefixlen 64  scopeid 0x20<link>
        ether 02:42:4d:5d:d9:04  txqueuelen 0  (Ethernet)
        RX packets 8225  bytes 476891 (465.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 46916  bytes 67959314 (64.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.40  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::13c2:ffb2:de88:5ff3  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:47:9b:24  txqueuelen 1000  (Ethernet)
        RX packets 26099184  bytes 5863334375 (5.4 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 21442718  bytes 5317704534 (4.9 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 3449680  bytes 242676624 (231.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3449680  bytes 242676624 (231.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth2363ee8: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 169.254.225.245  netmask 255.255.0.0  broadcast 169.254.255.255
        inet6 fe80::c1c2:ce98:2a42:d86d  prefixlen 64  scopeid 0x20<link>
        ether 42:f8:63:29:3e:1e  txqueuelen 0  (Ethernet)
        RX packets 1921808  bytes 959110872 (914.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1602937  bytes 113499953 (108.2 MiB)
        TX errors 0  dropped 2 overruns 0  carrier 0  collisions 0

veth47d0230: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 169.254.179.67  netmask 255.255.0.0  broadcast 169.254.255.255
        inet6 fe80::344c:89ff:fe0f:133d  prefixlen 64  scopeid 0x20<link>
        ether 36:4c:89:0f:13:3d  txqueuelen 0  (Ethernet)
        RX packets 704689  bytes 52740468 (50.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 868275  bytes 71151009 (67.8 MiB)
        TX errors 0  dropped 1 overruns 0  carrier 0  collisions 0

veth7726d82: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 169.254.224.92  netmask 255.255.0.0  broadcast 169.254.255.255
        inet6 fe80::24fb:5ff:fe0f:5187  prefixlen 64  scopeid 0x20<link>
        ether 26:fb:05:0f:51:87  txqueuelen 0  (Ethernet)
        RX packets 96182  bytes 6356679 (6.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 212914  bytes 27837282 (26.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth8a95ff8: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 169.254.199.179  netmask 255.255.0.0  broadcast 169.254.255.255
        inet6 fe80::9cf9:1bff:febf:da6d  prefixlen 64  scopeid 0x20<link>
        ether 9e:f9:1b:bf:da:6d  txqueuelen 0  (Ethernet)
        RX packets 10  bytes 1660 (1.6 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 58826  bytes 8438885 (8.0 MiB)
        TX errors 0  dropped 1 overruns 0  carrier 0  collisions 0

vetha0e4ef5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 169.254.226.79  netmask 255.255.0.0  broadcast 169.254.255.255
        inet6 fe80::ecec:8aff:fe66:4ea7  prefixlen 64  scopeid 0x20<link>
        ether ee:ec:8a:66:4e:a7  txqueuelen 0  (Ethernet)
        RX packets 8197  bytes 22499185 (21.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 306066  bytes 43949400 (41.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether b8:27:eb:12:ce:71  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by devgianlu** [comment]
Does it happen always with the same interface or is it random?

[This](https://stackoverflow.com/questions/1057224/java-thread-blocks-while-registering-channel-with-selector-while-select-is-cal) could be the issue, but I can't understand why it should be happening only to you.

**Comment by l3d00m** [comment]
From the very short investigation on that day I remember that it happened on the same interface. I'll come back to you in a few weeks, currently I've got no access to that raspberry, sorry.

**Comment by l3d00m** [comment]
I'll try to spin up that setup again in the next week, sorry for the very late reply.

**Comment by devgianlu** [comment]
Any news?

**Comment by l3d00m** [comment]
Sorry, not really. I've got too much on my mind currently to debug this :( Would it be alright for you if I close it for now, as I haven't managed to look into it now for a very long time?

**Comment by devgianlu** [comment]
No problem, go ahead
