### ISSUE TITLE
Support spotify's get-audio-features api endpoint

### ISSUE THREAD

**Issue by ikirmitz** [librespot-org/librespot-java#255]
**Is your feature request related to a problem? Please describe.**
Spotify calculates and stores a host of audio features for a track which are retrievable through the get-audio-features api 
Currently there doesn't seems to be a way to retrieve these features using the API provided by librespot-java 

**Describe the solution you'd like**
Allow retrieval of a track's audio features through the /metadata/{type}/{uri} or /metadata/{uri} endpoints or maybe through a completely new endpoint such as /audio-features/{uri}

**Additional resources**
More info here https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-features/

**Comment by devgianlu** [comment]
Unluckily this data isn't provided inside the client with an internal API endpoint. You need to use the public API to retrieve audio features.

**Comment by devgianlu** [comment]
What I could do is add an endpoint that resolves all the endpoints from the public API? Would that be a solution for you?

You could do `POST http://localhost:24879/web-api/v1/audio-features/{id}` and librespot-java will add the `Authorization` header.

**Comment by ikirmitz** [comment]
That is an amazing solution. Non having to deal a separate authentication is ideal!!

**Comment by devgianlu** [comment]
@ikirmitz I've made the changes, let me know if it works for you.

**Comment by ikirmitz** [comment]
It works perfectly. Thank you!
