### ISSUE TITLE
package com.spotifymvn does not exist

### ISSUE THREAD

**Issue by evesyinc** [librespot-org/librespot-java#264]
Hey,

I keep getting this error when running 'nvm compile':

`librespot-java-dev/lib/src/main/java/xyz/gianlu/librespot/Version.java:[5,29] package com.spotifymvn does not exist`

**Comment by devgianlu** [comment]
It should be `mvn compile`.

**Comment by evesyinc** [comment]
Thanks a lot, sorry!
