### ISSUE TITLE
API vs Player

### ISSUE THREAD

**Issue by evesyinc** [librespot-org/librespot-java#265]
Sorry for posting it here, but i couldn't find the answer clearly.
What is the exact difference between the API and the Player jar?

**Comment by devgianlu** [comment]
It has the same features as the player, but it creates an HTTP server that can do all kind of useful stuff: https://github.com/librespot-org/librespot-java/tree/dev/api

**Comment by evesyinc** [comment]
Great, thank you @devgianlu 

And how can these commands be executed?

**Comment by devgianlu** [comment]
You can call the endpoints with any HTTP client, you can see the curl examples at the bottom.

**Comment by evesyinc** [comment]
Ah okay, thank you!
