### ISSUE TITLE
Multiple instances on 1 server

### ISSUE THREAD

**Issue by evesyinc** [librespot-org/librespot-java#266]
Hey everyone,

Is it possible to run 2-3 instances of Librespot on 1 PC with the API version? Trying to make multiple devices for different persons in the house and I was wondering if/how this is possible.

**Comment by devgianlu** [comment]
That's definitely possible, make sure you set different values for `deviceName`, cache directory, credentials files and of course the API port. You can do that by editing the generated config file.

**Comment by evesyinc** [comment]
@devgianlu Thanks I managed to set it up on our server in the storage. Is it possible to use the API as well with a free account or do I need to have multiple premium ones to skip/play music from our main desk PC?

**Comment by devgianlu** [comment]
Free accounts are not supported, the API might work, but you might get your account suspended.
