### ISSUE TITLE
Config Path Discovery

### ISSUE THREAD

**Issue by paulbastian** [librespot-org/librespot-java#271]
**Is your feature request related to a problem? Please describe.**
Hello, I'm running my setup as a headless pi4, therefore I'm want to run librespot-java as a system service with systemd. I haven't found a way to pass a config path to the program, therefore the program generates a new `config.toml` at `/´

**Describe the solution you'd like**
I suggest any combination of:
- a command line parameter like `--config /path/to/my/config.toml`
- a series of fixed paths that are checked before building a new file in local repository, e.i. `/etc/librespot-java/config.toml` , `~/.config/librespot-java/config.toml`
 
I would also offer to provide AUR package for Arch Linux, therefore currently looking for the cleanest solutions possible.
Many thanks and best regards,
Paul

**Comment by devgianlu** [comment]
You can use `--conf-file=/path/to/my/config.toml`, I think that's undocumented.

**Comment by paulbastian** [comment]
This works indeed, thank you!
