### ISSUE TITLE
Please upload librespot-player 1.5.3 to maven repository

### ISSUE THREAD

**Issue by thorstenhaga-tradedoubler** [librespot-org/librespot-java#287]
Hej,

Please upload the last version ( v.1.5.3 ) librespot-player so that i can use it for my project :  

https://github.com/spocon/lovspotify/issues/14

maven repo: 
https://mvnrepository.com/artifact/xyz.gianlu.librespot/librespot-player

thanks and keep up the good work :-)

**Comment by devgianlu** [comment]
I forgot to release it on OOS. Will be available in a few hours.
