### ISSUE TITLE
Failure to play next song from 'Popular' list of artist

### ISSUE THREAD

**Issue by frodeseverin** [librespot-org/librespot-java#289]
**Describe the bug**
When connecting to librespot-java while playing first song in 'Popular' list of an artist, the next song from that list does not play.

**To Reproduce**
1. Close any running instances of librespot-java and Spotify app for Android
2. Start librespot-java in Zeroconf mode
3. Start Spotify app on Android phone
4. Find an artist
5. Start playing from top of 'Popular' list
6. Connect to librespot-java from 'Devices' menu in App on Android phone
7. Wait for next song to start
8. Observe that playing meter keeps running after song is finished and that next song in 'Popular' list is not played

**Expected behavior**
The next song in 'Popular' list should play after the first one

**Workaround**
1. Start a song from a playlist in bullet 4 above
2. Connect to librespot-java from 'Devices' list
3. Continue with bullet 5, skip 6, then 7 above
4. Observe that the next song in 'Popular' list is played as expected

**Screenshots/Stracktraces/Logs**
Se below

**Version/Commit**
Version used or commit pulled if compiled locally.
```
$ git branch -v
* dev f774052 Merge branch 'master' into dev
```

**Comment by frodeseverin** [comment]
Log from reproduction stage.
[runlibrespot_2021-01-04-21:54.log](https://github.com/librespot-org/librespot-java/files/5766865/runlibrespot_2021-01-04-21.54.log)

**Comment by frodeseverin** [comment]
Log from workaround.
[runlibrespot_2021-01-04-22:07.log](https://github.com/librespot-org/librespot-java/files/5766872/runlibrespot_2021-01-04-22.07.log)

**Comment by devgianlu** [comment]
Should be fixed with 727df6ad5b4f09c8c629659dea41fd2953f4e4ae.

**Comment by frodeseverin** [comment]
Situation is actually worse now.

**To reproduce**
1. Start librespot-java
2. Start Android App
3. Go to artist page
4. Start playing from 'Popular' list
5. Try to select librespot-java in devices list
6. Observe that connection is not made; song continues playing on Android App

**Workaround**
Same workaround as before: 
1. Play media from regular playlist
2. Connect to librespot-java
3. Play 'Popular' from artist's page

Log from problem:
[runlibrespot_2021-01-05-19:47.log](https://github.com/librespot-org/librespot-java/files/5772048/runlibrespot_2021-01-05-19.47.log)

Log from Workaround:
[runlibrespot_2021-01-05-19:55.log](https://github.com/librespot-org/librespot-java/files/5772052/runlibrespot_2021-01-05-19.55.log)

Log from problem + workaround + no problem anymore:
[runlibrespot_2021-01-05-20:01.log](https://github.com/librespot-org/librespot-java/files/5772076/runlibrespot_2021-01-05-20.01.log)

**Comment by frodeseverin** [comment]
It is also an issue when a new App with a different account tries to connnect.

**Reproduce**
1. Connect with one Android App and play media
2. Play some media on a different Android device with a different Spotify account and try to connect
3. Does not connect

**Workaround**
1. Connect with one Android App and play media
2. Play some media on a different Android device with a different Spotify account and try to connect
3. Does not connect
4. Play media from a different playlist on second device and try to connect
5. Connects fine and plays media on librespot-java

**Log from reproduce**
[runlibrespot_2021-01-05-20:12.log](https://github.com/librespot-org/librespot-java/files/5772269/runlibrespot_2021-01-05-20.12.log)
(rather lengthy, important bits toward the end)

**Log from workaround**
[runlibrespot_2021-01-05-20:41.log](https://github.com/librespot-org/librespot-java/files/5772275/runlibrespot_2021-01-05-20.41.log)

**Comment by devgianlu** [comment]
Try 0e85e1a52a1082dc1c63d79c432107bdeb9ed5b6

**Comment by frodeseverin** [comment]
Thank you much.

And thank you again for putting in all this effort in maintaining librespot-java.
