### ISSUE TITLE
Blocking of the process until the player load is complete

### ISSUE THREAD

**Issue by kokarare1212** [librespot-org/librespot-java#297]
**Is your feature request related to a problem? Please describe.**
Since it cannot detect when the player is finished loading, it cannot know when to terminate the program.

**Describe the solution you'd like**
Thread blocking process until the player finishes loading the music stream (like player.waitReady().get())

**Additional context**
Example
```java
public class Main(){
    public static void main(String[] args) {
        Session session = new Session.Builder()
                            .userPass("UserName", "Password")
                            .create();
        PlayerConfiguration playerConfiguration = new PlayerConfiguration.Builder()
                    .setOutput(AudioOutput.STDOUT)
                    .build();
        Player player = new Player(playerConfiguration, session);
        try{
            player.waitReady().get();
        } catch(InterruptedException e){
            e.printStackTrace();
        } catch(ExecutionException e){
            e.printStackTrace();
        }
        player.load("spotify:track:xxxxxxxxxxxxxxxxxxxxxx", true);
// Something to block it?
        try{
            session.close();
        } catch(IOException e){
            e.printStackTrace();
        }
        System.exit(0);
    }
}
```

**Comment by devgianlu** [comment]
You can use `Player#addEventsListener`.

Side note:
> We (the librespot-org organization and me) DO NOT encourage piracy and DO NOT support any form of downloader/recorder designed with the help of this repository and in general anything that goes against the Spotify ToS. If you're brave enough to put at risk this entire project, just don't publish it. This is meant to provide support for all those devices that are not officially supported by Spotify.

**Comment by kokarare1212** [comment]
`Player.Listener` could not catch that the music data output was completed.
The stdout outputs the following events.
```
Player.EventsListener#onContextChanged spotify:track:xxxxxxxxxxxxxxxxxxxxxx
Player.EventsListener#onTrackChanged TrackId{spotify:track:xxxxxxxxxxxxxxxxxxxxxx},null
Player.EventsListener#onPlaybackResumed 18
Player.EventsListener#onMetadataAvailable xyz.gianlu.librespot.player.TrackOrEpisode@3ed0a6d6
{Music Data}
Player.EventsListener#onPlaybackHaltStateChanged true,839
{Music Data}
Player.EventsListener#onPlaybackHaltStateChanged false,839
{MusicData}
...
```
I'd like to use it to play Spotify on my Discord bot.
> Side note:
>>We (the librespot-org organization and me) DO NOT encourage piracy and DO NOT support any form of downloader/recorder designed with the help of this repository and in general anything that goes against the Spotify ToS. If you're brave enough to put at risk this entire project, just don't publish it. This is meant to provide support for all those devices that are not officially supported by Spotify.

**Comment by devgianlu** [comment]
I have added the `onPlaybackEndend` event.

**Comment by kokarare1212** [comment]
Thank you for making the change.
