### ISSUE TITLE
running on Java desktop app

### ISSUE THREAD

**Issue by thilankapun** [librespot-org/librespot-java#301]
i have a problem to use library in my java desktop application , im not sure which libraries i need to add . please help me on this

**Comment by devgianlu** [comment]
Depends on what you need to do. The `library` package contains everything you need to interact with Spotify, but cannot play music on its own. The `player` package is built on top of `library` and can play music, that's also used as the default standalone versione. The `api` package is built on top of `player` and adds a REST API that you can use to control the client outside of the program itself.

More details can be found inside each package README.
