### ISSUE TITLE
Zeroconf spotify connect detection

### ISSUE THREAD

**Issue by snekiam** [librespot-org/librespot-java#32]
I'm having issues getting either my Android phone, linux laptop or windows laptop to discover my raspberry pi running librespot-java with zeroconf.  I'm able to connect to the pi running librespot-java when I enter my credentials into the configuration file, but this is not ideal.  The console for librespot-java does not show any connection attempts and hangs here when I attempt to use zeroconf.  
`2018-12-28 14:43:09 INFO  Utils:104 - Successfully removed cryptography restrictions.
2018-12-28 14:43:09 INFO  ZeroconfAuthenticator:204 - HTTP server started successfully on port 37694!
2018-12-28 14:43:13 INFO  ZeroconfAuthenticator:82 - SpotifyConnect service registered successfully!
`
Any ideas where I'm going wrong?  The rust version of the library works fine for me.

**Comment by devgianlu** [comment]
https://github.com/librespot-org/librespot-java/releases/tag/v0.1.2
