### ISSUE TITLE
Problem compiling on raspberry 3b. Am I doing something wrong?

### ISSUE THREAD

**Issue by aleszczynskig** [librespot-org/librespot-java#321]
**Describe the bug**
Please see the attached logs. There is a missing dependency. I do not know how to resolve this. Can you help?

**To Reproduce**
check out latest using git clone https://github.com/librespot-org/librespot-java.git
run mvn clean package in the root directory

**Expected behavior**

**Screenshots/Stracktraces/Logs**
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for librespot-java 1.5.6-SNAPSHOT:
[INFO]
[INFO] librespot-java ..................................... SUCCESS [  0.559 s]
[INFO] librespot-java lib ................................. FAILURE [  6.967 s]
[INFO] librespot-java player .............................. SKIPPED
[INFO] librespot-java api ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.637 s
[INFO] Finished at: 2021-02-26T13:41:02Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.6.1:compile (default) on project librespot-lib: Unable to resolve artifact: Missing:
[ERROR] ----------
[ERROR] 1) com.google.protobuf:protoc:exe:linux-arm_32:3.11.4
[ERROR]
[ERROR]   Try downloading the file manually from the project website.
[ERROR]
[ERROR]   Then, install it using the command:
[ERROR]       mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.11.4 -Dclassifier=linux-arm_32 -Dpackaging=exe -Dfile=/path/to/file
[ERROR]
[ERROR]   Alternatively, if you host your own repository you can deploy the file there:
[ERROR]       mvn deploy:deploy-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.11.4 -Dclassifier=linux-arm_32 -Dpackaging=exe -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR]
[ERROR]   Path to dependency:
[ERROR]   	1) xyz.gianlu.librespot:librespot-lib:jar:1.5.6-SNAPSHOT
[ERROR]   	2) com.google.protobuf:protoc:exe:linux-arm_32:3.11.4
[ERROR]
[ERROR] ----------
[ERROR] 1 required artifact is missing.
[ERROR]
[ERROR] for artifact:
[ERROR]   xyz.gianlu.librespot:librespot-lib:jar:1.5.6-SNAPSHOT
[ERROR]
[ERROR] from the specified remote repositories:
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)

**Version/Commit**
https://github.com/librespot-org/librespot-java/commit/3ab3c71435526b207fe584effd87932c55e47033

**Comment by devgianlu** [comment]
The problem is that there is no precompiled `protoc` binary for your platform. You need to download and [compile protoc](https://github.com/protocolbuffers/protobuf/blob/master/src/README.md) yourself and then execute `mvn clean package -DprotocExecutable=/path/to/compiled/protoc`.

**Comment by aleszczynskig** [comment]
Great. Thanks for your help.
