### ISSUE TITLE
Issue pfls event to metadata pipe when pausing, stopping or changing tracks 

### ISSUE THREAD

**Issue by aleszczynskig** [librespot-org/librespot-java#325]
**Is your feature request related to a problem? Please describe.**
Can you issue a pfls command to the shairport-sync style metadata pipe when either pausing, stopping or changing track. This enables forked-daapd to immediately pause as opposed to a significant delay or 4-5 seconds before the command is observed in forked-daapd due to the audio stream ending. I have requested @ejurgensen to implement this feature in forked-daapd which has been done (see [issue 295](https://github.com/ejurgensen/forked-daapd/issues/295#issuecomment-795593458)). Many thanks.

**Describe the solution you'd like**
Issue a 'pfls' event to the configured metadata pipe when pausing, stopping or changing track.

**Describe alternatives you've considered**
None

**Additional context**
The command required to be issued is `<item><type>73736e63</type><code>70666C73</code><length>0</length></item>`

**Comment by devgianlu** [comment]
What is `<item><type>73736e63</type><code>70666C73</code><length>0</length></item>` for? Pause, stop or track change?

**Comment by aleszczynskig** [comment]
It's the pfls command. It instructs forked-daapd to drop the content on the audio buffer (which removes the lag). So the same command can be issued for all of them.

Thanks for looking at this.

**Comment by devgianlu** [comment]
Got it. Let me know if it works

**Comment by aleszczynskig** [comment]
This is working exactly as expected. Thank you for the quick fix. When using librespot-java with forked-daapd, the controls are really responsive. 

I will close the ticket.
