### ISSUE TITLE
toggle shuffle via API

### ISSUE THREAD

**Issue by aebgit** [librespot-org/librespot-java#330]
First of all, thanks for the great project! It is community-projects like yours that make tech way more useful!

**Is your feature request related to a problem? Please describe.**
Triggering of playlists-playback via API should have an option to toggle shuffle-mode.
I trigger playback of certain playlists via the `librespot-java` API from [Homebridge](https://homebridge.io) via [homebridge-http-switch](https://github.com/Supereg/homebridge-http-switch#readme) plugin. 
It is a bit annoying over time, when my playlists always start with the 1st song in the list.

Example:
```
{
     "url": "http://localhost:24879/player/load",
     "method": "POST",
     "body": "uri=spotify:playlist:6w7Lsb0JCGEq8f2pBgoZtr&play=true",
     "headers": {
          "Content-Type": "application/json"
     }
}
```

**Describe the solution you'd like**
It would be great to have an option to start playback via API in shuffle-mode. Maybe you could consider something like the example below, which adds a `shuffle`-parameter to the API request, that could be either true or false.: 
```
{
     "url": "http://localhost:24879/player/load",
     "method": "POST",
     "body": "uri=spotify:playlist:6w7Lsb0JCGEq8f2pBgoZtr&play=true&shuffle=true",
     "headers": {
          "Content-Type": "application/json"
     }
}
```

**Describe alternatives you've considered**
I've already tried to play with `shuffle=true|false` and  `shuffle_state=true|false`, inspired by the [Official Spotify API](https://developer.spotify.com/documentation/web-api/reference/#category-player).

**Additional context**
I usually trigger these playlists when I come home or to wake up in the morning through Homebridge via Apple HomeKit, so I'm not using the Spotify client for that. Later I open Spotify on my phone or computer and change the playlists during the day.
The tool-chain for playback looks as follows:

Apple HomeKit - [Homebridge](https://homebridge.io) - [homebridge-http-switch](https://github.com/Supereg/homebridge-http-switch#readme) - [SPOCON](https://github.com/spocon/spocon) - [LIBRESPOT](https://github.com/librespot-org/librespot-java) - [forked-daapd/OWNTONE](https://github.com/owntone/owntone-server) - AirPlay - HomePods

For the sake of completeness, the tool-chain for volume-control looks as follows:

Apple HomeKit - [Homebridge](https://homebridge.io) - [homebridge-http-rgb-push](https://github.com/QuickSander/homebridge-http-rgb-push#readme) - [forked-daapd-homebridge-middleware](https://github.com/moecre/forked-daapd-homebridge-middleware) - [forked-daapd/OWNTONE](https://github.com/owntone/owntone-server) - AirPlay - HomePods

Everything is running super smooth on a RaspberryPi 3.

Thanks in advance for giving me some directions or considering the feature!
Andreas

**Comment by devgianlu** [comment]
I have added a `shuffle` parameter to the `/player/load` endpoint (100d248c1c94595f76f94364b2f94bd8f217c098) and also supplied two more endpoints to toggle shuffling and repeating separately (7747677641993c012e72135ee3d38ea48591f326). 

P.S. I love how people are integrating librespot-java in their home setups!

**Comment by aebgit** [comment]
Thank you for the superfast response, thats awesome!
Here my results with the new build.
The new endpoint works as expected:
`curl -X POST -d "val=true" http://localhost:24879/player/shuffle`
`curl -X POST -d "val=false" http://localhost:24879/player/shuffle` 

But the shuffle-toggle included in `player/load`is not working.
`curl -X POST -d "uri=spotify:playlist:6w7Lsb0JCGEq8f2pBgoZtr&play=true&shuffle=true" http://localhost:24879/player/load`
When I watch my Spotify-client (MacOS) in parallel, the shuffle-icon is green for a split-second but is then disabled again before the music starts.

**Comment by devgianlu** [comment]
Should be good now.

**Comment by aebgit** [comment]
Awesome :-)
Thank you and have a great easter-time!
