### ISSUE TITLE
No new build available due to Travic CI error "Owner librespot-org does not have enough credits."

### ISSUE THREAD

**Issue by Zageron** [librespot-org/librespot-java#334]
![image](https://user-images.githubusercontent.com/1892473/114196930-b0344080-9906-11eb-88e1-bf5f91b12565.png)
ETA on new release? :)

**Comment by devgianlu** [comment]
I hate Travis and their new open source policy. I tried emailing them about the project but it's been more than 2 months and no response. Will move to GitHub Actions.

**Comment by devgianlu** [comment]
I've now moved it to GitHub actions. The snapshot should be available eventually.
