### ISSUE TITLE
Use SLF4J API's as a facade to Log4J in lib-module

### ISSUE THREAD

**Issue by mitschwimmer** [librespot-org/librespot-java#335]
**Is your feature request related to a problem? Please describe.**
I am experimenting with using the lib-module on Android. Log4J can't be easily used there, as explained here: https://loune.net/2016/05/using-log4j2-2-3-with-android/

**Describe the solution you'd like**
I would like the classes in the lib-module to use SLF4J API's instead of Log4J. I found an actively maintained SLF4J Adapter here https://github.com/nomis/slf4j-android (although seemingly limited to SLF4j 1.7x)

**Describe alternatives you've considered**
Maybe there is a logging solution which would be working great with Android and the modern JVM. But I assume that you would like to stick to log4j. SLF4J as a facade would make that possible.

**Additional context**
I would like to try this approach. I can offer a PR if you are interested.

**Comment by devgianlu** [comment]
Would #336 be a solution for you?

**Comment by mitschwimmer** [comment]
Definately. I am amazed how quickly you did that. Thanks!
