### ISSUE TITLE
librespot-player as thin JAR

### ISSUE THREAD

**Issue by mitschwimmer** [librespot-org/librespot-java#340]
**Is your feature request related to a problem? Please describe.**
I want to integrate the player module in an Android Gradle Project and Android Studio is getting all mixed up due to the librespot-player jar being a fat JAR.

**Describe the solution you'd like**
Please provide the player additionally as a JAR unbundled from its dependencies so that I can let gradle manage the whole dependency graph.
I am currently defining my dependency to the player like this: `implementation 'xyz.gianlu.librespot:librespot-player:1.5.6-SNAPSHOT'`. So maybe it could be something along the lines of `implementation 'xyz.gianlu.librespot:librespot-player-thin:1.5.6-SNAPSHOT'` to get to the thin JAR.

**Describe alternatives you've considered**
I do not see alternatives.

**Comment by devgianlu** [comment]
I am trying to understand how to do that in a decent way. I have managed to compile the Android app with librespot-player by marking the dependency as non-transitive (see https://github.com/devgianlu/librespot-android/commit/c79df9574d19e28de9f5ef484f3eb89a36efb0ff), but then you'll encounter another issue which can be solved by raising the min API to 26 (I have not pushed that).

**Comment by mitschwimmer** [comment]
Interesting. The problematic dependency with my kotlin code seems to be that 'kotlin' as a library is shipped with librespot-players fat jar. So it does work with the java example you made, but it will not in a Kotlin project. If you look at my [MainActivity.kt](https://github.com/mitschwimmer/spoddler/blob/ffa128060e9e9c4333ad88de7a3b359fbccfdcbc/app/src/main/java/de/mitschwimmer/spoddler/MainActivity.kt#L11) in the IDE you will see that the class 'Player' cant be imported. And that the compiler fails,  hinting that the bundled kotlin will probably be an issue. 

Apart from there being an actual issue; I think it would be preferable to have librespot-players dependencies declared rather than bundled. The jar is clocking in with ~10MB and has some stuff in it almost no Android App would need.

[Update: removed screenshot]

**Comment by devgianlu** [comment]
I agree. There should be a way to get the thin/skinny jar. The fat jar is useful because one can just download it and run it.

Maven does produce the jar without dependencies during the build process, but I cannot figure out how to push it to nexus separately. If you want you can build locally and then grab it from the target folder. Meanwhile I'll try to figure out a solution for Maven.

**Comment by devgianlu** [comment]
@mitschwimmer Finally published a thin jar. You can include it with `implementation('xyz.gianlu.librespot:librespot-player:1.5.6-SNAPSHOT:thin')`, you might as well run `gradle build --refresh-dependencies`.

I have made a semi-functional setup on my repo: https://github.com/devgianlu/librespot-android/commit/9465c6203b351c2417696b89256cb6f083c3dedf, but then it crashes at runtime.

**Comment by mitschwimmer** [comment]
@devgianlu as thin as I had hoped for, thanks!
