### ISSUE TITLE
Support custom decoders

### ISSUE THREAD

**Issue by funtax** [librespot-org/librespot-java#343]
I am using librespot-java on an ARM-based device with a custom implementation of the VorbisCodec (ARM-optimized tremolo-decoder).
Would it be possible to make the VorbisCodec configurable like you did with the output-sink?

If this is possible I could contribute to the [Android-project](https://github.com/devgianlu/librespot-android) and provide my custom optimized decoder there.

**Comment by devgianlu** [comment]
That's a nice idea. We should have support for plug-in decoders, something like Java SPI. I'll add support for that, in the meantime feel free to make a PR to librespot-android with a new module for the decoder.

**Comment by funtax** [comment]
Thank you in advance. I will try to contribute the required files somehow. It's likely that I cannot provide a complete module because I only have an hour of spare-time at the evening right now :-/

**Comment by devgianlu** [comment]
No worries, if you can put the code there I'll patch it up.

**Comment by funtax** [comment]
You are awesome, thank you 😎

**Comment by funtax** [comment]
@devgianlu I am just testing this, looks good so far but the constructor of "xyz.gianlu.librespot.player.codecs.Codec" is package-private. This requires custom codecs to use package "xyz.gianlu.librespot.player.codecs".
Maybe you want to add a "public" here :)

**Comment by devgianlu** [comment]
@funtax Fixed

**Comment by funtax** [comment]
Thanks @devgianlu , found another two required classes :)

    public static class CannotGetTimeException extends Exception {
        *public* CannotGetTimeException() {
        }
    }

    public static class CodecException extends Exception {
        *public* CodecException() {
        }
    }

**Comment by devgianlu** [comment]
@funtax Fixed once again. I have modified the constructor to have an error message (and a parent exception optionally).

**Comment by funtax** [comment]
Thank you very much @devgianlu !
