### ISSUE TITLE
Player/Device Volume Enhancement

### ISSUE THREAD

**Issue by MorningSage** [librespot-org/librespot-java#369]
**Is your feature request related to a problem? Please describe.**
Trying to use custom “slider” controls that update the volume in real time as you move your mouse controls the device volume correctly but spams the server with unneeded volume update requests.

**Describe the solution you'd like**
Ideally, there would be a simple way to control both the device volume and notify Spotify of the volume change separately (for instance, on a mouse up event).

**Describe alternatives you've considered**
I’ve attempted to use reflection to access the fields manually so that I can set the device volume myself and update the server after, but my quick and dirty tests didn’t seem to work well.  I could probably do it with enough effort but I’m not horribly familiar with the internal workings of the code yet.

**Additional context**
I’m using an instance of the Player class to do the majority of the work here which seems to work well, but doesn’t give me the fine tuned control (unless I’m missing it?) that I need.  The end goal is to let the user use a slider to change the volume in real time and then update the server after the user decides on the right volume (like I said, a mouse up event).

If I’m not clear, I can try to elaborate a bit more.

**Comment by devgianlu** [comment]
I think I am missing a step here. librespot-java has no UI and the interaction between the Desktop client slider and librespot-java is not something we can control.

**Comment by MorningSage** [comment]
You are correct, I am implementing the slider.

I can control the interaction of the slider, but what I can't seem to control is the ability to change the device volume (the volume that librespot-java is playing the audio at) separately and limit the the number of times the the updated volume is sent to the Spotify servers.

For instance, I would like the user to use my slider to update the volume live while they are dragging their mouse around.  If the user drags the slider from 100% down to 50%, I want to be able to have the audio playback reflect the change live.  The method I am using is `xyz.gianlu.librespot.player.Player:setVolume` and the I am able to hear the gradual change in volume perfectly.  However, looking at other devices, I can see that the volume goes from 100% to 99% to 98%, etc, etc.  And it keeps going long after I have finished adjusting the volume in the Gui I am creating.

The proposed solution/enhancement I was trying to verbalize is to have a method can be called when I want to change the playback volume and a separate one to send the updated volume to the Spotify servers.  While dragging the slider control around, I can update the playback volume and when the user's mouse button is released, I can then send the selected volume to the server so that it reflects correctly on all the other devices.  This would avoid unnecessary spam to the servers.

Maybe this is already implemented and I'm just missing it?

**Comment by devgianlu** [comment]
I guess it could make sense to have the client send the update to the server once the user has finished dragging the slider around and reflect the change only locally while it's dragging.

I'll play around with it to see how it behaves.

**Comment by devgianlu** [comment]
@MorningSage The volume update is now sent to the server after 500ms of the last volume change so that if the volume keeps changing it is reflected only locally.

**Comment by MorningSage** [comment]
That's perfect!

Thanks I think that will fix the issue I was experiencing.

**Comment by sashahilton00** [comment]
This might be a bit late/unhelpful, but it may be worth adding a flag at either compile/runtime for this such as `--buffer-events` as iirc delays in UI updates of less than 100ms are generally not perceived, whereas updates that take longer than that can be noticeable and impact overall UX.

**Comment by devgianlu** [comment]
@sashahilton00 I tried playing around with the delay a bit, but at 200ms the updates were already going straight to the server because apparently the client is already spacing them auto a little bit. Secondly, this doesn't not affect the UX on the client you are changing the volume on because the slider stays in the position you moved it to and receives the update before it tries to go back to the original position. I guess you'd see the update delay if you were watching another client than the one you are using to change the volume.
