### ISSUE TITLE
Minimizing audio pop with owntone + metadata pipe

### ISSUE THREAD

**Issue by yepitschunked** [librespot-org/librespot-java#389]
As mentioned in https://github.com/owntone/owntone-server/issues/295#issuecomment-797052704, the metadata pipe support makes owntone much more responsive. However, there's a distracting ~0.2s of audio pop at the start of every user-initiated track change. My guess of what's happening is this:

1. owntone has its own internal buffer of 2s of audio
2. upon receiving the flush message, owntone clears its buffer and continues to read from pipe
3. however, unless we got lucky with perfect alignment between the flush event and start of the new track audio arriving, the pipe will contain `[end of last song----|----start of new song-------]`. owntone blindly plays this data (since it's just a dumb pipe) and we get the pop.

I think this is fundamentally hard to solve because because the metadata change and the contents of the audio pipe are not in sync, and owntone has no idea when the next song is starting (it's just playing the contents of the pipe). However, I think silence/some additional delay would be preferable to the noise. 

I couldn't find an event in the player code that corresponded to the new stream actually starting (onTrackChanged is fired immediately), so onMetadataAvailable seemed like the next best thing. Moving the `dacpPipe.sendPipeFlush();` call here minimized the sound to a brief click, which makes me feel like this hypothesis is on the right track. However, moving it here kinda sucks because it really ought to be a track change callback, and it affects non user-initiated track changes too. 

Wondering if you have some ideas. I *think* the ideal time to send the flush message would be right before the new track audio is about to be written to the pipe.

**Comment by devgianlu** [comment]
(sorry for the late reply)

I have added an `onFinishedLoading` listener [here](https://github.com/librespot-org/librespot-java/commit/5607c5d43edbfdf70295f627a03976f9dbab46ab#diff-7fe18bf702012fd05470360ea16897ac36fb1bdafc68bb6be6eb3568b76ce339R1050). That should be the closest thing to the first bytes being written to the output. Let me know how it works so that I can change where the flush happens with another commit.

**Comment by foxy82** [comment]
Hi - I just tried this out and can confirm that removing:
`if (userInitiated) dacpPipe.sendPipeFlush();`
from `onTrackChanged`

And adding:
`dacpPipe.sendPipeFlush();`
to `onFinishedLoading`

Changes it from an obvious 2 seconds of the previous track to a tiny/v. short crackle sound.


my git diff:

```
diff --git a/player/src/main/java/xyz/gianlu/librespot/player/Player.java b/player/src/main/java/xyz/gianlu/librespot/player/Player.java
index 7f049b8..bddf2db 100644
--- a/player/src/main/java/xyz/gianlu/librespot/player/Player.java
+++ b/player/src/main/java/xyz/gianlu/librespot/player/Player.java
@@ -981,7 +981,7 @@ public class Player implements Closeable {
 
                     @Override
                     public void onTrackChanged(@NotNull Player player, @NotNull PlayableId id, @Nullable MetadataWrapper metadata, boolean userInitiated) {
-                        if (userInitiated) dacpPipe.sendPipeFlush();
+//                        if (userInitiated) dacpPipe.sendPipeFlush();
                     }
 
                     @Override
@@ -1052,6 +1052,7 @@ public class Player implements Closeable {
 
                     @Override
                     public void onFinishedLoading(@NotNull Player player) {
+                        dacpPipe.sendPipeFlush();
                     }
                 });
             }

```
