### ISSUE TITLE
Wrong track timestamp on Spotify client while outputting to a Pipe

### ISSUE THREAD

**Issue by MwenDavo** [librespot-org/librespot-java#395]
**Describe the bug**
When I call the play() function with a song already loaded and the player configured to output to a file, from the Spotify desktop client I can see that the timestamp goes from 0:00 to 0:01, then to 0:00, then to 0:02 and then to 0:00 again. After a few seconds, the song skips itself and the app shows a message indicating that the song couldn't be played.

**To Reproduce**
Follow the base player setup and specify the Pipe output to a file on the Configurator. After that, load a song and play it.

**Expected behavior**
I guess it should follow the timestamp correctly, streaming the PCM raw data to the file accordingly to the chunks loaded by the player.

**Version/Commit**
Player version 1.6.1

**Comment by efung1232** [comment]
I do see the message "the song couldn't be played". But, I do not see the "jerking" in progress bar.

**Comment by efung1232** [comment]
The message actually is "Spotify can't play this right now. If you have the file on your computer ou can import it." However, the song is indeed playing fine. I thiink the message shows up if song is started by "play/next". If the playlist is keep going, this message will not be shown.

**Comment by MwenDavo** [comment]
Unfortunately, I lost my code for the project that had this error, so I can't replicate it anymore. I'll mark the issue as closed, but if anyone happens to stumble upon the same behavior, please open it again.
