### ISSUE TITLE
When creating new session, stuck at ap resolver

### ISSUE THREAD

**Issue by KagChi** [librespot-org/librespot-java#455]
**Describe the bug**
Cannot connect, stuck at ap resolver

**To Reproduce**
Using https://github.com/librespot-org/librespot-java/tree/dev/lib example
Some code snipped i used, https://hastebin.de/wurexutoqo.java

**Expected behavior**
Should connected to spotify

**Screenshots/Stracktraces/Logs**
![image](https://user-images.githubusercontent.com/59391215/150899461-273a33c7-ae7f-4989-b1b9-d1f762c62374.png)
**Version/Commit**
v1.6.2

**Comment by iscle** [comment]
Without seeing your code it's hard to know if it's an issue with your implementation or librespot-java itself. I think the issue is you're not instantiating the player correctly.

**Comment by KagChi** [comment]
> Without seeing your code it's hard to know if it's an issue with your implementation or librespot-java itself. I think the issue is you're not instantiating the player correctly.

no? its still not connecting even i instantiating the player. the issue fixed if i instantiating session without session builder.
 
the code i use is using the example in the readme https://github.com/librespot-org/librespot-java/tree/dev/lib

**Comment by devgianlu** [comment]
Try removing the locale, I'm not sure whether `US` is a valid locale. Also how do you know it's not connecting to Spotify?

**Comment by KagChi** [comment]
![image](https://user-images.githubusercontent.com/59391215/153124461-dc9e3fd7-2753-4731-bce5-068a764b7574.png)
if its connected the logs will show this,

**Comment by KagChi** [comment]
> Try removing the locale, I'm not sure whether `US` is a valid locale. Also how do you know it's not connecting to Spotify?

thanks, that fixes my issues
