### ISSUE TITLE
PlaylistId lacks of fromBase62() method.

### ISSUE THREAD

**Issue by JCGdev** [librespot-org/librespot-java#458]
**Describe the bug**
PlaylistId lacks of `fromBase62(@NotNull String base62)` method, when the rest
of classes that implement SpotifyId do have it.

**Version/Commit**
**librespot-api-1.6.2.jar**

**Comment by devgianlu** [comment]
That's because the playlist URI format isn't directly compatible with base62 encoding. Closing in favour of #443. If a base62 method is needed it'll be added. They might have changed URIs completely, not sure.
