### ISSUE TITLE
Difference between librespot-api and librespot-player

### ISSUE THREAD

**Issue by Katzenwerfer** [librespot-org/librespot-java#486]
I'm not exactly sure what the difference in functionality and purpose is.
So far, it looks like both do essentially the same when run.

**Comment by Katzenwerfer** [comment]
Also, sorry for the bug label
I wasn't exactly sure what to label this as

**Comment by devgianlu** [comment]
librespot-api exposes some endpoints as stated here: https://github.com/librespot-org/librespot-java/blob/dev/api/README.md
