### ISSUE TITLE
Sound disappears after 1 sec after switching stream to librespot-java's spotify connect

### ISSUE THREAD

**Issue by wendellgee** [librespot-org/librespot-java#491]
Hi,

First of all many thanks for the great library which, together with easyeffects, enables my entire home audio setup.

Running into a problem with Ubuntu 22.04 on RPi 4.
Switching Spotify stream to librespot-java Spotify Connect from any source (Spotify app on phone or laptop) succeeds, the sound appears, then after same interval of about 1 second disappears. Nothing brings the sound back except switching the stream to other Spotify Connect receiver (e.g. phone app) and back to librespot-java. After 1 second the sound disappears again.
Same behavior running librespot-java as a daemon through spocon or from command line directly.

No problems with librespot 0.3.1 650d41b (non-java).
All other apps (e.g. VLC, Chromium) do not have any issues with audio output.

On 3 other RPis librespot-java 1.6.2 works just fine, including on pipewire (ubuntu 21.10)

Raspberry Pi 4 8Gb / Ubuntu 22.04 arm64 
PulseAudio (on PipeWire 0.3.48)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 48000Hz
librespot-java-api-v1.6.2.jar

Happy to provide whatever logs are helpful.

**Comment by iscle** [comment]
Can you see any stacktrace or error getting printed in the console?

**Comment by wendellgee** [comment]
Nothing i would recognize as an error. Attaching the log piece, starting from pressing 'play' button in Spotify app on my phone to the moment when the sound disappears. Interestingly, if i put the song on pause and start again - no sound; if i wait ca 20 seconds and start again - sound appears for 1 s and disappears again.

[librespot-java-2022May11.log](https://github.com/librespot-org/librespot-java/files/8672337/librespot-java-2022May11.log)

**Comment by garis** [comment]
With `output = "MIXER"` I noticed this problem. In my case taking the first non-defult mixer name from the output (they are shown in the output log before starting the sound) and placing it into `mixerSearchKeywords` solve this issue.
Example: `mixerSearchKeywords = "PCH [plughw:0,0]"`

**Comment by wendellgee** [comment]
Thank you for the idea, garis. It took a bit of time to get back to it and now, after a few ubuntu updates, the problem has disappeared. Closing this issue.
