### ISSUE TITLE
Client does not resume the playback after reconnection

### ISSUE THREAD

**Issue by xMordax** [librespot-org/librespot-java#50]
I came to notice that while my server stack was updating, including the raspberry pi where the librepost-java client is running, it disconnected me from my Spotify Desctop Client and it stopped playing music(seemed like it paused the music)... but from the logs it seems like librepost-java client lost connection to the internet and disconnected.
After the conversation with @devgianlu it seems like the reconnection worked correctly but it didn't resume the playback.

Here the logs:
[librespot-java2.log](https://github.com/librespot-org/librespot-java/files/2949220/librespot-java2.log)
[librespot-java.log](https://github.com/librespot-org/librespot-java/files/2949221/librespot-java.log)

**Comment by devgianlu** [comment]
Can you explain what exactly you did? What I understood (partially from `librespot-java2.log`):
- Was playing some music
- Internet disconnected (how?)
- Reconnected to `librespot-java` using SpotifyConnect
- Started playing music again

**Comment by xMordax** [comment]
Each Sunday my server reg will perform unattended system upgrades.
Here were the steps I did:
* ```librespot-java``` was running.
* I connected to it over my main computer with ```ZEROCONF```.
* Started listening to few songs and all of a suddon it disconnected me from my main computer(I was still able to see the ```librespot-java``` as spotify connect)
* Tried reconnecting few times until it eventually worked
* Started the song from the beginning 
* Till it again it paused and disconnected me from the ```librespot-java``` spotify connect.

Like you can see it started happening around 9:45~10:00, meanwhile I got an email from my unattended upgrades at 9:46 which then all made sense and I knew it was probably a problem with internet connection. 
Strange is just that the connection to ```librespot-java``` spotify connect broke because of it, the behavior that I expected would be that the ```librespot-java``` spotify connect, keeps the connection to the client(my case, my main computer) and just has a timeout till the connection to the Spotify servers is back and afterwards continues.

Maybe we are missing some timeout parameters?

**Comment by xMordax** [comment]
PS: packages that were upgraded today: 
``` openssh-client openssh-server openssh-sftp-server ssh```
I dont think these would cause any trouble with the ```librespot-java``` client.

**Comment by devgianlu** [comment]
I've just experienced this myself and managed to get some logs. I need to understand how to cause this behavior to do some debugging. 

Whenever I try to cause manually it works flawlessly.

[Log for reference](https://pastebin.com/eGEs3avh)

**Comment by devgianlu** [comment]
I've added one single line of logging and hopefully this is the issue. Could you recompile and send a log after reproducing the issue?

**Comment by xMordax** [comment]
I am back Tuesday.
I will try creating network I/O load on my server reg with some integration tests and see what happens...
will report back.

**Comment by xMordax** [comment]
@devgianlu I tried to throw everything at him, my whole LAN was unusable because my integration tests made too much load, so that the Desktop Spotify Client could not even communicate with librespot-java, there was a huge latency in the Network I/O, but the librespot-java just kept on playing as much as he was able too... I will keep an eye on this problem, maybe it occurs again on Sunday, lets see...

**Comment by devgianlu** [comment]
@xMordax Did you see this issue again?

**Comment by xMordax** [comment]
I will close this ticket since I think the problem got solved and I created https://github.com/librespot-org/librespot-java/issues/56 anyway.
