### ISSUE TITLE
Unable to choose HDMI output mixerSearchKeywords doesn't filter properly

### ISSUE THREAD

**Issue by ysguy** [librespot-org/librespot-java#502]
`ubuntu@ubuntu:/var/log$ aplay -L |grep plughw
plughw:CARD=PCH,DEV=0
plughw:CARD=PCH,DEV=3
plughw:CARD=PCH,DEV=7
plughw:CARD=PCH,DEV=8
plughw:CARD=PCH,DEV=9
plughw:CARD=PCH,DEV=10
`

Dev=0 is the analog output, librespot chooses this by default. 

I've tried
- Editing that /etc/asoundrc
- Changing the user it runs under to the active logged in user
- Setting the default ubuntu sound output (pulse) to the right card
- mucking around extensively with the mixerSearchKeywords

Logging shows:
INFO  LineHelper:90 - Available mixers: 'PCH [plughw:0,0]', 'PCH [plughw:0,3]', 'PCH [plughw:0,7]', 'PCH [plughw:0,8]', 'PCH [plughw:0,9]', 'PCH [plughw:0,10]'

I can't for the life of me get anything other than the default to select.

have tried keywords

"plughw;7"
"7"
"PCH:0,7"
"PCH;[plughw:0.7]"

Nothing works. 

How can i know what the program is using for the sound output, it always just shows "Available Mixers" but doesn't say anything like "Using mixer:" or "Selecting card:"

is there a way to just say instead of searching, just use X?

Also, yes i've tested with speakertest etc and know that output works.

**Comment by ysguy** [comment]
I have a workaround (sort of): 

Running with this command: 

`/usr/bin/java -jar /opt/spocon/librespot-java-api-v1.6.2.jar --backend pulseaudio`

works with pulse, using the default output for that user.  Note: it does not work from systemd. even though i chose it to run as the logged in user, it appears to not use that same session. So i'll just make it a startup script when the user logs in.

**Comment by devgianlu** [comment]
librespot-java doesn't support any `backend` configuration, there must be something else going on. How are you setting the search keyword?

**Comment by ysguy** [comment]
I'm an idiot. First of all this was a Spocon issue, but i was on the wrong tab of my browser. Second of all it works now. I think a few reboots and a kernel update solved it. Editing the /etc/asound.conf wasn't working, but after reboots it does work. I also learned that librespot/spocon needs complete access to the soundcard and i run Kodi on the machine as well, so if Kodi is idle all works well. Anyways, close the case, it all works a-ok!
