### ISSUE TITLE
Two issues regarding player

### ISSUE THREAD

**Issue by xMordax** [librespot-org/librespot-java#60]
I found 2 issues:
 First:
* If the Spotify Client has no song selected(or playlist) it does not connect to librespot-java client

Second (See #61): 
* Play a song from the top list from an artist on librespot-java client
* Switch to the songs Album
* It does not switch

**Comment by devgianlu** [comment]
First:
How do you force Spotify to have no selected song? I think it does that only when it updates. Can you reproduce this systematically?

Second:
I actually knew about this issue, but forgot to fix it.

**Comment by xMordax** [comment]
I am not sure, sometimes my desktop Linux Spotify client is empty, I think it happens when I shutdown/reboot my computer without closing the Spotify client beforehand.

**Comment by xMordax** [comment]
@devgianlu 
I tried the new master branch regarding the album playing problem. It still does not work for me. It started to play a song in the middle of the album and when I pressed the next song it played a random song from that band.

**Comment by devgianlu** [comment]
Fixed one issue, #61 is open for the other one.
