### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by arifainchtein** [librespot-org/librespot-java#67]
Hello,
I downloaded librespot-java because i want  to use the raspberry pi to get music from spotify and send it to play on a bluetooth speaker attached to the pi.  I want to be able to play, pause and skip next and back fro a playlist in spotify using a java program or a command line.
Is this posible with librespot-java?  
I have downloaded everything and i can succesfully start librespot.  Here is a dump 👍 
![Screen Shot 2019-04-02 at 13 45 54](https://user-images.githubusercontent.com/7456552/55372549-d8d21480-554d-11e9-96f2-235e65d09ca1.png)

As you can see, i was authenticated propery with spotify.
What is the next step?
How can I start playing a song using the command line or a java call?  I dont want any gui at all, i want to be all code/cli base is this posible?  Any examples?

thanks

**Comment by devgianlu** [comment]
From your Spotify client, you should see a device named `librespot-java`, click on it to connect.

**Comment by arifainchtein** [comment]
oh, maybe i dont understand the purpose of librespot.  
I did go to spotify in my iphone and i can see that in the devices there is one called librespot-java and if i click on it, i can hear the music playing.  I was hoping to eliminate the iphone.  I was going to use ilibrespot-java in a raspberry pi with physical toggle buttons attach to the gpio of the pi.  
I was going to write code that when the human togles the switch, it will send a message to spotify.  

Is there a way to do that?  

I have the api-client running, but in the connect field all it shows is
`ws://`

i tried setting the field to 127.0.0.1 and cick connect, i get a message it was rejected
if i set the field to 127:0;0.1:44043 (44043 is the port that it seems to be using) it connectes and cloes the connetion inmediately.
What should it go in that field?

thanks

**Comment by devgianlu** [comment]
To use the `api-client`, you need to run `librespot-api`. To connect then use `ws://localhost:24879`. 

You should be able to control the playback in it's basic functionalities.

**Comment by arifainchtein** [comment]
wow, got it working.  I started the librespot-api, then librepot-client-api and connected via localhost:24879., clicked play and it played
Now for the $64000 dollar question.  
I still had to go to my iphone and the select the librespot-java device.  Is there a way to send a message so that it automatically select that device?  this is so that when i am running it in the pi, all i would have to do is toggle a button, and code in the pi will detect the toggle and say , start playing the song in my local speaker, without having to select the device in the iphone.

Thanks , is really nice the work you have done

**Comment by arifainchtein** [comment]
oh, sorry one more little thing. If i had bluetooth speakers connected to the pi, hwo do you differentiate between the audio port and the bluetooth speakers?

**Comment by devgianlu** [comment]
Now for the $64000 dollar question.


Unlucky, I think it's not possible. You need a full featured client to control a client. Once it's connected, you can control the playback.

To change the output device see https://github.com/librespot-org/librespot-java/issues/40#issuecomment-453613404

**Comment by elganzua124** [comment]
I'm using linux mint 19.1, jdk 12 installed, when I run the command:

`java -jar librespot-api-client-jar-with-dependencies.jar`

I got:

`Error: JavaFX runtime components are missing, and are required to run this application`

Isn't JavaFX included with the standard JDK and JRE bundles?

**Comment by elganzua124** [comment]
Nevermind, I just downloaded the JavaFX package and pointed the path is located in the command line.
There isn't a cli client?

**Comment by devgianlu** [comment]
> Just a question, there isn't a cli client?

Not yet, maybe after I've completed #65

**Comment by elganzua124** [comment]
Great! My idea is to put the rpi in a box with some buttons to control the playback and restart the service if it hangs, and a display to see current track.

**Comment by arifainchtein** [comment]
Well, I tried your #40 and it worked very nicely. 
I was looking at the other two handlers, Mercury and Metadata. I could not find documentation on either one but   I think i figured it out how to use the metadata to get the rootlist, from there to get the playlist and then to get track info.
Three questions:
1)When I send the metadata playlist with the id, i get a list of the ids of all the tracks, but i dont get the name of the playlist. is there a way to get the playlist name?
2)When I press play and a track starts playing, how do i get the id of the currently playing track so i can then use that to get the metadata?
3)Is there any documentation on how to use the Mercury Handler?

I figured how to do 2 maybe there is a better way. What i did is modify the load method in TrackHandler to add a couple of lines that save a text fule to the hard drive with the current info.  
Hre is the code:

`JsonObject data = new JsonObject();
 data.addProperty("Name", track.getName());
 data.addProperty("Artist", Utils.artistsToString(track.getArtistList()));
 data.addProperty("Album", track.getAlbum().getName());
 FileUtils.writeStringToFile(new File("CurrentSong.txt"), data.toString());`

The problem with this approach is that i need to recompile and recreate the librespot-core which is used by librespot-api.
Is there a better way?  Ideally one where the info is in the librespot-api code base?

@elganzua124 I am doing the same thing with the raspberry pi a you mentioned, but i probably will put an arduino with the pi zero to handle other things besides catching the toggle buttons.
I will be working on some form of cli client, but mst likely embeded in my application framework. 

Thanks

**Comment by devgianlu** [comment]
> When I send the metadata playlist with the id, i get a list of the ids of all the tracks, but i dont get the name of the playlist. is there a way to get the playlist name?

This requires investigation. Currently, there's no way to do that.

> When I press play and a track starts playing, how do i get the id of the currently playing track so i can then use that to get the metadata?

I've added the `currentTrack` endpoint to the player handler (`player.currentTrack`) to retrieve metadata about the current song.

> Is there any documentation on how to use the Mercury Handler?

I'll try to find some time to create the docs

**Comment by devgianlu** [comment]
Reopen if you need help again.
