### ISSUE TITLE
Implement seek of MP3 stream

### ISSUE THREAD

**Issue by devgianlu** [librespot-org/librespot-java#68]
Seems to be working with current master.

Also remember to fix [this](https://github.com/librespot-org/librespot-java/blob/0f1ffb5c65d404cb4460ae23bb73001fbb2edfbf/core/src/main/java/xyz/gianlu/librespot/player/codecs/Mp3Codec.java#L94).

**Comment by xMordax** [comment]
Quick question, what feature is this, is it possible to play custom MP3s?

**Comment by devgianlu** [comment]
It is needed to play podcasts from the CDN (currently I've switched to the Spotify servers because I'm not entirely sure the MP3 codec works correctly).

**Comment by elganzua124** [comment]
> It is needed to play podcasts from the CDN (currently I've switched to the Spotify servers because I'm not entirely sure the MP3 codec works correctly).

Is it possible that some episodes fail to load because of that? For example, [this one](https://open.spotify.com/episode/04XPBNQX6S9bhKsvA7xhFK?si=ZLwOHGnnR5ubII8rx0mdhQ).

**Comment by devgianlu** [comment]
@elganzua124 Is that a video episode? `librespot-java` can't play them yet.

**Comment by elganzua124** [comment]
No, there isn't. Just an audio episode. On my laptop I can hear it normally. Maybe I should open a new issue.

**Comment by devgianlu** [comment]
>Maybe I should open a new issue.

Do.

**Comment by devgianlu** [comment]
I've fixed the seeking issue [here](https://github.com/devgianlu/JavaMP3/commit/f5d351eaeec48967ea1d6a15db70bb4dd91b9f2b), but upon [research](https://stackoverflow.com/a/7268043/5446197) I found that retrieving the exact position from an MPEG stream is impossible.

Therefore the preload feature is disabled for MP3 streams (mainly episodes). 0c401cf8fa6a4fe6a75d357e5d3002af71b20d5f
