### ISSUE TITLE
new  type of uri ? (BUG) 

### ISSUE THREAD

**Issue by thedtvn** [librespot-org/librespot-java#683]
**Is your feature request related to a problem? Please describe.**
I use search API and get  some weird  uri 

**Describe the solution you'd like**
update  uri regex

**Additional context**
![image](https://github.com/librespot-org/librespot-java/assets/80153297/9e05b763-3480-4838-a2e7-76f455bf3680)
![image](https://github.com/librespot-org/librespot-java/assets/80153297/5aa730ae-a077-4337-a3ed-fdcd96ad89d2)

**Comment by thedtvn** [comment]
update  is  all like  this 
![image](https://github.com/librespot-org/librespot-java/assets/80153297/188c3037-ba46-4f7b-af09-32791f7235c0)

**Comment by thedtvn** [comment]
sory  i set wrong Labels😅

**Comment by christosk92** [comment]
First version of playlists have the owners username in them.
So it’s spotify:user:(ownerId):playlist:(playlistId)

PlaylistsV2 are in the regular format: 
spotify:playlist:(playlistId)

A regex you might be able to use is:

```
spotify:user:(?<userId>.+):playlist:(?<playlistId>.+)

```
