### ISSUE TITLE
Detect when playback halts

### ISSUE THREAD

**Issue by devgianlu** [librespot-org/librespot-java#76]

**Comment by loeffelpan** [comment]
Yesterday I noticed, that librespot stops the playback when preloading fails. Thats good as the user can just restart playback or choose another song to play.

But when loading a chunk failed even after retrying (as you implemented in #74) librespot has to be restarted before it can be used again.

Couldn't you handle ChunkExeptions the same way you handle PreloadingExecptions?

**Comment by devgianlu** [comment]
> Couldn't you handle ChunkExeptions the same way you handle PreloadingExecptions?

When a `ChunkExeption` is thrown the player enters the stopped state. From there you can select another song.
