### ISSUE TITLE
 missing formats 

### ISSUE THREAD

**Issue by 3052** [librespot-org/librespot-java#857]
formats 18 19 missing

https://github.com/librespot-org/librespot-java/blob/d0ff31b4f476590c9c17401aac01a6762e4ba908/lib/src/main/proto/metadata.proto#L262-L274

**Comment by devgianlu** [comment]
Do you know what they are?

**Comment by 3052** [comment]
I thought you guys pulled from the windows client:
https://github.com/librespot-org/librespot/blob/dev/protocol/proto/spotify/login5/v3/login5.proto#L1

is that no longer possible?

**Comment by devgianlu** [comment]
Yeah, but I do not usually keep it updated if not necessary to implement new stuff.

I've updated the definition over at go-librespot: https://github.com/devgianlu/go-librespot/commit/1a58df1b9cd5b30a930cdfe529dceb72af7ce6f1
