### ISSUE TITLE
Compiling error (Missing JavaFX dependency)

### ISSUE THREAD

**Issue by loeffelpan** [librespot-org/librespot-java#86]
Hey,
got this on compiling 0.5.2.

```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project librespot-api-client: Compilation failure
[ERROR] /home/osmc/librespot-java/api-client/src/main/java/xyz.gianlu.librespot.api.client/ResponseDialogController.java:[3,20] cannot access javafx.scene.Node
[ERROR] bad class file: /home/osmc/.m2/repository/org/openjfx/javafx-graphics/12ea+8/javafx-graphics-12-ea+8-linux.jar(javafx/scene/Node.class)
[ERROR] class file has wrong version 55.0, should be 52.0
[ERROR] Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Comment by devgianlu** [comment]
I cannot reproduce this on Ubuntu with the latest commit.

**Comment by loeffelpan** [comment]
Hmm, first time I tried to compile this directly on my RPi.
Java is OpenJDK8. Maybe that‘s the issue?

Compiling (like before) on my Ubuntu works (with OpenJDK10).

**Comment by devgianlu** [comment]
OpenJDK8 doesn't include JavaFx (https://github.com/AdoptOpenJDK/openjdk-build/issues/577), install JavaFX in your system or run `mvn -pl '!api-client' package` to skip the module that requires the dependency.

**Comment by loeffelpan** [comment]
Thanks.
Does this mean, that api-client wouldn’t work anyway on this device?
Then I would run `mvn -pl core,common package` and build without api, api-client and interactive-cli. Would that work?

**Comment by devgianlu** [comment]
The `api-client` module will refuse to compile until you install JavaFX on the system. 

> Then I would run mvn -pl core,common package and build without api, api-client and interactive-cli. Would that work?

Should work totally fine.
