### ISSUE TITLE
Error on loading another album.

### ISSUE THREAD

**Issue by loeffelpan** [librespot-org/librespot-java#93]
Got some error with the latest commit.
I started librespot freshly and loaded/played a playlist. Fine so far.
Then I tried to load another album.
Nothing happend and after some attempts I got disconnected from librespot and cannot connect anymore.

Here is the trace.
https://pastebin.com/7u8HJExd

The very first error appeared when selecting to unshuffle in iOS app.

**Comment by devgianlu** [comment]
How many songs does the playlist contain? More than 400?

**Comment by loeffelpan** [comment]
Okay. I‘ll have a look on it and report.

**Comment by loeffelpan** [comment]
Faced this issue again 😞 
https://pastebin.com/yW0sCiKn

This time I switched from my mixtape to an playlist.

**Comment by devgianlu** [comment]
This had to do with big playlists and apparently the iOS app which sends all the tracks to the client (other clients send only 80), the current fix is not ideal as stated in #95.
