### ISSUE TITLE
Shuffle/Unshuffle

### ISSUE THREAD

**Issue by loeffelpan** [librespot-org/librespot-java#94]
Faced something like #15 with latest commit.
But it's not a playlist, it's an album.

Can't exactly reproduce this.
I tried to playback an audiobook and it was shuffled, wheather shuffle was selected in app or not.

Maybe you can see something in the trace?
https://gist.github.com/loeffelpan/8744829b733def394033860de81b0f5b

**Comment by devgianlu** [comment]
So librespot wasn't shuffling/unshuffling the album? Correct?

**Comment by loeffelpan** [comment]
Correct.
As you can see in the trace it played „Teil 01“ (engl. part) and then some other „Teil“ but not 02. And I swear shuffle was disabled.

**Comment by devgianlu** [comment]
I was not able to figure out what happened from the log. I've added some logging on the latest master, hopefully you can catch this again. (I think I also experienced this myself)

**Comment by loeffelpan** [comment]
I will try and give you feedback. Thanks.
Concerning to this: Can you explain what „defaultUnshuffleBehaviour“ in properties mean? Maybe related to this?

**Comment by devgianlu** [comment]
This option, if enabled, will force the client to not unshuffle a playlist if it hasn't been shuffled by the client itself. I've removed that option and it can be considered always disabled. To unshuffle, the client will fetch the original playlist and restore it or use the shuffle seed if available.

**Comment by loeffelpan** [comment]
At the moment everything is shuffled at any time.
Here are the logs with new build.

https://gist.github.com/loeffelpan/b3153bbf762b01bebf2c66eae55d7e5a

I noticed (better to see in windows client) that the unshuffled order of song is the same (when toggling shuffle on and off). But it's not the original order the album/audiobook/mixtape is displayed.

**Comment by devgianlu** [comment]
I noticed a pretty simple mistake in the code, let me know if it works now.

**Comment by loeffelpan** [comment]
Closed to it!
There must be the same mistake in another line of your code.

With last commit the first load of songs were in the correct order.
After shuffle and unshuffle them once, they're in wrong order as before.

**Comment by devgianlu** [comment]
Turns out it was an issue with the track uri parsing.

**Comment by loeffelpan** [comment]
Working now fine.
Thanks.
