### ISSUE TITLE
Playback pause on loading track

### ISSUE THREAD

**Issue by loeffelpan** [librespot-org/librespot-java#96]
When connected with librespot the playback halts on loading a track.
I would guess that playback should continue if playing before. For now I have to press play again.

Maybe related to this:
Sometime the play state is wrong on loading iOS app (was closed before). Playback is active but the app shows play button, not pause. Pressing play solves this.

`player.enableLoadingState` is set so false for me.

**Comment by loeffelpan** [comment]
Unfortunately not solved.
Do you need a stacktrace?

**Comment by devgianlu** [comment]
Yup, it should definitely start playing if it's not the first song to be loaded when connected, unless otherwise specified by the client.

**Comment by loeffelpan** [comment]
Hmm okay.
Here is my stacktrace.
https://pastebin.com/RVRMhr9v

I start playback on my iPhone and then connected to librespot: playback halts on loading the first song.
While connected I could change between playlists/albums while playing.

Is it designed like this?
I think this was possible in one of the previous versions.

**Comment by devgianlu** [comment]
I had it in mind that way, but I realized it doesn't make much sense.

**Comment by loeffelpan** [comment]
Wonderful.
Now it works like I would expect.
Thanks!
