### ISSUE TITLE
Please provide a Jar file for the 1.64 release

### ISSUE THREAD

**Issue by iVolt1** [librespot-org/librespot-java#992]
**Describe the bug**

Prior releases for librespot-java provide a jar file for direct downloading from the releases.  The jar file is used by the Home Assistant Homepod Connect addon which has good user base and is one the better and easier ways to achieve multi-room Spotify audio through Owntone.

Please provede a Jar file for the 1.64 release so the addon will continue to work.

I greatly appreciate your continuing support for librespot-java.  There is currently no drop-in replace for libresport java that can send audio and metadata through a pipe to Owntone and also has a Home Assistant control api.  I hope these features will be implemented in librespot-golang so it can be a drop in replacement for the Homepod Connect addon.

Thanks,
iVolt1

**Comment by devgianlu** [comment]
My bad, I published the wrong release. Should be fixed now: https://github.com/librespot-org/librespot-java/releases/tag/v1.6.4
